### ISSUE TITLE
Where to edit tthe config.js file?

### ISSUE THREAD

**Issue by MaartenDrenth** [danielwippermann/resol-vbus#100]
Can you explain in detail where to do this?

You must edit the file config.js to adapt it to your environment. See the file for details.

I do not know where to find this file.. sorry.

**Comment by dm82m** [comment]
The “where” heavily depends on your setup and can’t be answered in general here.

If you have specific questions about the “how” the configuration is done, you are at the right place.

**Comment by danielwippermann** [comment]
Hi @MaartenDrenth !

@dm82m Thanks for your quick response!

As Dirk already mentioned it depends on how you use the json-live-data-server.

If you plan to run it standalone you would simply follow the installation instructions on the README of the json-live-data-server:

https://github.com/danielwippermann/resol-vbus/blob/master/examples/json-live-data-server/README.md

The last step copies an example configuration file (including comments for all important fields) into the file "config.js" which you can edit afterwards before starting the server for the first time.

But if you plan to use the json-live-data-server that is embedded in some other appliance (like Dirk's HomeAssistant plugin) you will have to follow the respective documentation of the appliance.

Best regards,
Daniel
