### ISSUE TITLE
USB Erkennung

### ISSUE THREAD

**Issue by pogo01** [danielwippermann/resol-vbus#101]
Moin, 
Wie gestern schon gepostet habe ich Probleme.
Danke für Eure tolle Arbeit und die Hilfe.

![Fehler 2](https://github.com/danielwippermann/resol-vbus/assets/120756465/f6a6730a-59d9-49e1-ba0e-99c0e5ed6aee)
![fehler](https://github.com/danielwippermann/resol-vbus/assets/120756465/6bae0812-871c-4cc4-9eed-e629c9130526)
![visuell studio](https://github.com/danielwippermann/resol-vbus/assets/120756465/1e3e9468-7e24-48ff-bb38-43e1bb5d5a60)
![lsusb](https://github.com/danielwippermann/resol-vbus/assets/120756465/d198ecbd-e11b-4fee-a014-009fd2df1898)

Dazu gibt es anscheinend noch Fehler in der config.js

**Comment by dm82m** [comment]
poste mal bitte deine komplette config.js hier. das was deine log ausgabe sagt, passt nicht zu dem ausschnitt deines config files. also fangen wir damit an.

**Comment by pogo01** [comment]
Ich fürchte wir müssen früher anfangen. Anscheinend wird dort nicht richtig installiert.
![da](https://github.com/danielwippermann/resol-vbus/assets/120756465/c6aa8574-a6ac-4949-93d9-3adaec499c8e)
liegt das auch am USB-Port?

**Comment by dm82m** [comment]
Ich versteh nicht was du tust. Warum installierst du irgendwas manuell? Wenn du das resol-vbus addon nutzt und die km2 Integration dann musst du nichts machen außer config files anpassen. Lies bitte die jeweiligen dokus noch mal genau.

**Comment by pogo01** [comment]
Danke werde ich machen

**Comment by pogo01** [comment]
Moin 
Ich bin froh, dass sich dass jemand ansieht.

1.Versuch über ESP
![esp](https://github.com/danielwippermann/resol-vbus/assets/120756465/6e123033-f1f9-46e0-b5a8-25835e944014)


2. Versuch über VBUS/USB Adapter




/*! resol-vbus | Copyright (c) 2013-present, Daniel Wippermann | MIT license */

const path = require('/dev/ttyACM0');



const config = {

    /**
     * The level of details for log messages.
     * @type {String}
     */
    logLevel: 'debug',

    /**
     * The port number for the HTTP server to listen to.
     * @type {Number}
     */
    httpPort: 3333,

    /**
     * The inteval in milliseconds between two writes of the logging file.
     * @type {Number}
     */
    loggingInterval: 10000,

    /**
     * The filename of the logging file.
     * @type {String}
     */
    loggingFilename: path.resolve(__dirname, 'live-data.json'),

    /**
     * Text file logging interval in milliseconds. A value of zero disables this functionality.
     */
    textLoggingInterval: 0,

    /**
     * Text file logging time to live in milliseconds.
     */
    textLoggingTimeToLive: 60000,

    /**
     * Text file logging directory.
     */
    textLoggingPath: path.resolve(__dirname, 'log'),

    /**
     * Text file logging options, passed to the `TextConverter` constructor.
     */
    textLoggingOptions: {
        columnSeparator: '\t',
        lineSeparator: '\r\n',
        separateDateAndTime: false,
    },

    /**
     * Either 'TcpConnection' or 'SerialConnection' to connect to the VBus.
     * @type {String}
     */
    connectionClassName: 'TcpConnection',

    connectionOptions: {
        /**
         * SerialConnection only:
         * The serial port to which the Vbus/USB device is connected.
         * @type {String}
         */
        path: '/dev/ttyACM0',

        /**
         * TcpConnection only:
         * The host name / IP address of the VBus/LAN or Datalogger device.
         * @type {String}
         */
        host: '192.168.188.66',

        /**
         * TcpConnection only:
         * The password for the VBus/LAN or Datalogger device.
         * @type {String}
         */
        password: 'vbus',
    },

    /**
     * A map of packet field IDs to their custom name.
     */
    packetFieldNameMap: {
        '00_0010_7E11_10_0100_000_2_0': 'Temperature collector',  // instead of "Temperater sensor 1"
    },

    /**
     * A list of EM (extension module) sub-addresses to simulate.
     */
    emSimulatorSubAdresses: [
        // 1,
        // 2,
        // 3,
        // 4,
        // 5,
    ],

};




Log:

![log](https://github.com/danielwippermann/resol-vbus/assets/120756465/6517027d-99cc-4fa2-8233-3cd87e4fa028)

**Comment by dm82m** [comment]
`connectionClassName: 'TcpConnection'` bitte ändern auf `connectionClassName: 'SerialConnection'

und warum genau hast du das hier geändert: `const path = require('/dev/ttyACM0');` - wo steht dass das du das ändern sollst? Bitte wieder zurück auf `const path = require('path');`

dann addon Neustart und log posten.

**Comment by pogo01** [comment]
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
--- VERSIONS ---
add-on version: 0.0.7
nodejs version: v21.7.1
npm version: 10.5.0
--- DEVICES ---
ls: cannot access '/dev/ttyUSB*': No such file or directory
/dev/ttyACM0
--- json-live-data-server ---
/bin/resol-vbus/examples/json-live-data-server/config.js:63
    connectionOptions: {
    ^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier 'connectionOptions'
    at internalCompileFunction (node:internal/vm:128:18)
    at wrapSafe (node:internal/modules/cjs/loader:1279:20)
    at Module._compile (node:internal/modules/cjs/loader:1331:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/bin/resol-vbus/examples/json-live-data-server/index.js:28:16)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)

Node.js v21.7.1
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by danielwippermann** [comment]
Fehlt am Ende der Zeile vor 63 vielleicht ein Komma am Ende?

**Comment by dm82m** [comment]
Okay, nimm bitte das Original config file noch mal und passe exakt die folgende Sache an und ansonsten veränderst du nichts!!!

connectionClassName: 'TcpConnection' bitte ändern auf connectionClassName: 'SerialConnection'

**Comment by pogo01** [comment]
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
--- VERSIONS ---
add-on version: 0.0.7
nodejs version: v21.7.1
npm version: 10.5.0
--- DEVICES ---
ls: cannot access '/dev/ttyUSB*': No such file or directory
/dev/ttyACM0
--- json-live-data-server ---
debug: Starting server...
debug: Connect to VBus data source...
error: Main function returned with error:
error: TypeError: ConnectionClass is not a constructor
    at main (/bin/resol-vbus/examples/json-live-data-server/index.js:663:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by pogo01** [comment]
/*! resol-vbus | Copyright (c) 2013-present, Daniel Wippermann | MIT license */

const path = require('path');



const config = {

    /**
     * The level of details for log messages.
     * @type {String}
     */
    logLevel: 'debug',

    /**
     * The port number for the HTTP server to listen to.
     * @type {Number}
     */
    httpPort: 3333,

    /**
     * The inteval in milliseconds between two writes of the logging file.
     * @type {Number}
     */
    loggingInterval: 10000,

    /**
     * The filename of the logging file.
     * @type {String}
     */
    loggingFilename: path.resolve(__dirname, 'live-data.json'),

    /**
     * Text file logging interval in milliseconds. A value of zero disables this functionality.
     */
    textLoggingInterval: 0,

    /**
     * Text file logging time to live in milliseconds.
     */
    textLoggingTimeToLive: 60000,

    /**
     * Text file logging directory.
     */
    textLoggingPath: path.resolve(__dirname, 'log'),

    /**
     * Text file logging options, passed to the `TextConverter` constructor.
     */
    textLoggingOptions: {
        columnSeparator: '\t',
        lineSeparator: '\r\n',
        separateDateAndTime: false,
    },

    /**
     * Either 'TcpConnection' or 'SerialConnection' to connect to the VBus.
     * @type {String}
     */
    connectionClassName: 'SerialConnection',

    connectionOptions: {
        /**
         * SerialConnection only:
         * The serial port to which the Vbus/USB device is connected.
         * @type {String}
         */
        path: '/dev/ttyACM0',

        /**
         * TcpConnection only:
         * The host name / IP address of the VBus/LAN or Datalogger device.
         * @type {String}
         */
        host: '192.168.188.66',

        /**
         * TcpConnection only:
         * The password for the VBus/LAN or Datalogger device.
         * @type {String}
         */
        password: 'vbus',
    },

    /**
     * A map of packet field IDs to their custom name.
     */
    packetFieldNameMap: {
        '00_0010_7E11_10_0100_000_2_0': 'Temperature collector',  // instead of "Temperater sensor 1"
    },

    /**
     * A list of EM (extension module) sub-addresses to simulate.
     */
    emSimulatorSubAdresses: [
        // 1,
        // 2,
        // 3,
        // 4,
        // 5,
    ],

};

**Comment by danielwippermann** [comment]
Da fehlt das `module.exports = config;` am Ende der Datei...

**Comment by dm82m** [comment]
Deswegen sagte ich: original config 1:1 nehmen und nur diese eine einzige Stelle anpassen. So macht mir das hier keinen Spaß @pogo01

**Comment by pogo01** [comment]
Danke für die Geduld. Sorry

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
--- VERSIONS ---
add-on version: 0.0.7
nodejs version: v21.7.1
npm version: 10.5.0
--- DEVICES ---
ls: cannot access '/dev/ttyUSB*': No such file or directory
/dev/ttyACM0
--- json-live-data-server ---
debug: Starting server...
debug: Connect to VBus data source...
info: Ready to serve from the following URLs:
info:     - http://127.0.0.1:3333/api/v1/live-data (internal)
info:     - http://172.30.33.4:3333/api/v1/live-data
debug: HeaderSet complete
debug: HeaderSet complete

**Comment by dm82m** [comment]
Damit läuft jetzt das add-on und du kannst dich der Home Assistant Integration widmen. Halte dich da bitte 1:1 an der Doku bzgl. Der config und verändere ansonsten nichts.

**Comment by pogo01** [comment]
Danke sehr.

**Comment by pogo01** [comment]
![Unbenannt](https://github.com/danielwippermann/resol-vbus/assets/120756465/25f330bc-367f-46d0-8302-f81a95574844)

Nochmals Vielen Dank

Over and Out

**Comment by araym2k** [comment]
Hallo,
habe leider auch ein Problem, wo ich nicht weiter komme aber ihr mir bestimmt sofort helfen könnt und sagt....wie dumm bist du :D
Es kommt dieser Fehler, das er die config nicht findet
![Image](https://github.com/user-attachments/assets/c08d436c-4d58-476a-b524-8491e0f96baf)


habe die Ordner erstellt und die Datei auch, so wie ich es verstanden habe. Und habe dann sogar nochmal einen Ordner config erstellt und dort die Datei rein, weil ich die Fehlermeldung dann so verstanden hatte aber leider wollte es immer nicht funktionieren? Wo muss diese Datei denn hin?
![Image](https://github.com/user-attachments/assets/84253ed6-56a1-492b-b134-b2fa8db10692)

![Image](https://github.com/user-attachments/assets/d306fea1-6d06-43aa-8b88-db89fc3fefbf)

Vielen dank und ich hoffe mir kann jemand weiter helfen :)
