### ISSUE TITLE
Direktes Auslesen per Uart

### ISSUE THREAD

**Issue by bastiiiii** [danielwippermann/resol-vbus#102]
Hallo miteinander,

bin gerade auf dieses Projekt gestoßen, als ich nach der Doku vom VBus gesucht habe.
Ich habe mir damals um 2015/16 in C was kleines geschrieben, womit mein RPi die Resol-Einheit per Uart direkt ausliest und alle 5 Minuten in eine sqlite schreibt.. Dargestellt wird es mittels highchartsJS in einer simplen html... Mir war damals der Converter einfach zu teuer ukd war heilfroh als ich das Protokoll umgesetzt bekommen hatte.

Mein momentanes Ziel ist es, die Daten in Homeassistant einzubringen und das Auslesen mit einem kleinen ESP zu erledigen.
Nun steh ich gerade, etwas überfordert des Projektstatuses hier, auf dem Schlauch und überlege, kann ich das Projekt direkt nutzen? Oder wie stellen die VBus-USB/ VBus-LAN Dinger die Daten zu Verfügung? Beim USB wird ja auch eine Serielle Schnittstelle in der config definiert.

Sehe zwei Optionen:
- Ich muss die Daten wie die Herstellergeräte aufbereiten.
- Ich muss das Projekt anpassen.

Oder denke ich zu kompliziert?!

Schon jetzt einmal ein Danke!

**Comment by danielwippermann** [comment]
Hallo @bastiiiii !

Es gibt schon eine gute HomeAssistant-Integration für RESOL VBus-Geräte: https://github.com/dm82m/hass-Deltasol-KM2

Die Integration kommt mit diversen Schnittstellenadaptern von RESOL zurecht. Dafür benutzt sie eines der Examples aus diesem Repo, den "json-live-data-server". Wie man diese beiden Bestandteile installiert und konfiguriert ist in der README der HomeAssistant-Komponente gut erklärt.

LAN-basierte VBus-Schnittstellenadapter benutzen normalerweise einen "VBus-over-TCP"-Handshake (siehe https://danielwippermann.github.io/resol-vbus/#/md/docs/vbus-over-tcp) , bevor die eigentlichen VBus-Daten fließen, den Dein ESP jetzt nicht ohne weiteres könnte. Du könntest jetzt also hergehen und diesen Handshake implementieren, aber theoretisch müsste auch ein anderer Weg gehen: man müsste nämlich diesen Handshake in der "json-live-data-server"-Konfiguration mit `rawVBusDataOnly: true` abschalten können... Getestet habe ich das allerdings nicht, weil ich kein HomeAssistant hier habe.

Denn wenn das geht, bräuchte Dein ESP die über die UART empfangenen Daten nur über einen TCP-Port "weiterreichen". Der "json-live-data-server" würde dann also mit `rawVBusDataOnly: true` Deinen ESP connecten, die Daten von dort empfangen, dekodieren und an die HomeAssistant-Komponente weitergeben.

Bis dann,
Daniel

**Comment by bastiiiii** [comment]
Hallo @danielwippermann,

vielen Dank für die schnelle und hilfreiche Antwort!
So in etwa habe ich mir das mittlerweile auch etwas gedacht. Habe nur überlegt, welcher Weg der wohl beste ist und du/ ihr hier viel tiefer in der Materie seid, als ich je war. Ich war froh als ich das VBus-Protokoll hinbekommen hatte damals, dann hat es aber auch aufgehört...

Das heißt aber auch, normal müsste ich doch auf den noch laufenden RaspberryPi mit deinem json-live-data-server doch jetzt auch direkt von /dev/tty.. lesen können oder?
Immerhin muss ich durch eure Arbeit nicht das Rad neuerfinden...

Ich werde das mal probieren und gerne nochmal Feedback für evtl. andere Interessierte geben.

**Comment by danielwippermann** [comment]
Hallo @bastiiiii,

> Das heißt aber auch, normal müsste ich doch auf den noch laufenden RaspberryPi mit deinem json-live-data-server doch jetzt auch direkt von /dev/tty.. lesen können oder?

Ja, richtig. Du nimmst - wie in der README beschrieben - die `config.js.example` als Vorlage, änderst Zeile 61 von `TcpConnection` auf `SerialConnection` und trägst in Zeile 69 Deinen Serial-Port ein. Dann sollte es schon einmal Daten von dort empfangen, dekodieren und je nach Konfiguration weiterverarbeiten bzw. per Web-API zur Abfrage zur Verfügung stellen.

Wenn dazu noch Fragen aufkommen, immer her damit :)

Bis dann,
Daniel

**Comment by bastiiiii** [comment]
Hi,

oh man, wenn es wirklich so einfach geht, dann spare ich mir ja richtig viel Zeit und Arbeit...
Allerdings hänge ich gerade daran, dass ich nodejs nicht auf den RPi2-Raspian installiert bekomme...

Bedarf es einer bestimmten Version? Ich habe bisher nur v10 laufbar bekommen und alles darüber mag nicht laufen...
