### ISSUE TITLE
errror

### ISSUE THREAD

**Issue by freddy357** [danielwippermann/resol-vbus#103]
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
--- VERSIONS ---
add-on version: 0.0.7
nodejs version: v22.3.0
npm version: 10.8.1
--- DEVICES ---
/dev/ttyUSB0
/dev/ttyACM0
--- json-live-data-server ---
debug: Starting server...
debug: Connect to VBus data source...
error: Main function returned with error:
error: Error: Unable to connect
    at onSocketTermination (/bin/resol-vbus/src/tcp-connection.js:368:26)
    at Socket.onError (/bin/resol-vbus/src/tcp-connection.js:401:17)
    at Socket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
--- VERSIONS ---
add-on version: 0.0.7
nodejs version: v22.3.0
npm version: 10.8.1
--- DEVICES ---
/dev/ttyUSB0
/dev/ttyACM0
--- json-live-data-server ---
debug: Starting server...
debug: Connect to VBus data source...
error: Main function returned with error:
error: Error: Unable to connect
    at onSocketTermination (/bin/resol-vbus/src/tcp-connection.js:368:26)
    at Socket.onError (/bin/resol-vbus/src/tcp-connection.js:401:17)
    at Socket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
--- VERSIONS ---
add-on version: 0.0.7
nodejs version: v22.3.0
npm version: 10.8.1
--- DEVICES ---
/dev/ttyUSB0
/dev/ttyACM0
--- json-live-data-server ---
debug: Starting server...
debug: Connect to VBus data source...
error: Main function returned with error:
error: Error: Unable to connect
    at onSocketTermination (/bin/resol-vbus/src/tcp-connection.js:368:26)
    at Socket.onError (/bin/resol-vbus/src/tcp-connection.js:401:17)
    at Socket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

/*! resol-vbus | Copyright (c) 2013-present, Daniel Wippermann | MIT license */

const path = require('path');

const config = {

    /**
     * The level of details for log messages.
     * @type {String}
     */
    logLevel: 'debug',

    /**
     * The port number for the HTTP server to listen to.
     * @type {Number}
     */
    httpPort: 3333,

    /**
     * The inteval in milliseconds between two writes of the logging file.
     * @type {Number}
     */
    loggingInterval: 10000,

    /**
     * The filename of the logging file.
     * @type {String}
     */
    loggingFilename: path.resolve(__dirname, 'live-data.json'),

    /**
     * Text file logging interval in milliseconds. A value of zero disables this functionality.
     */
    textLoggingInterval: 0,

    /**
     * Text file logging time to live in milliseconds.
     */
    textLoggingTimeToLive: 60000,

    /**
     * Text file logging directory.
     */
    textLoggingPath: path.resolve(__dirname, 'log'),

    /**
     * Text file logging options, passed to the `TextConverter` constructor.
     */
    textLoggingOptions: {
        columnSeparator: '\t',
        lineSeparator: '\r\n',
        separateDateAndTime: false,
    },

    /**
     * Either 'TcpConnection' or 'SerialConnection' to connect to the VBus.
     * @type {String}
     */
    connectionClassName: 'TcpConnection',

    connectionOptions: {
        /**
         * SerialConnection only:
         * The serial port to which the Vbus/USB device is connected.
         * @type {String}
         */
        path: '/dev/ttyACM0',
    },

    /**
     * A map of packet field IDs to their custom name.
     */
    packetFieldNameMap: {
        '00_0010_7E11_10_0100_000_2_0': 'Temperature collector',  // instead of "Temperater sensor 1"
    },

    /**
     * A list of EM (extension module) sub-addresses to simulate.
     */
    emSimulatorSubAdresses: [
        // 1,
        // 2,
        // 3,
        // 4,
        // 5,
    ],

};

module.exports = config;

**Comment by danielwippermann** [comment]
Please retry after replacing your `connectionClassName: 'TcpConnection'` with `connectionClassName: 'SerialConnection'`.

**Comment by freddy357** [comment]
Didnot do it.

error: Error: Unable to connect
    at onSocketTermination (/bin/resol-vbus/src/tcp-connection.js:368:26)
    at Socket.onError (/bin/resol-vbus/src/tcp-connection.js:401:17)
    at Socket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections
(node:internal/process/task_queues:82:21)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
--- VERSIONS ---
add-on version: 0.0.7
nodejs version: v22.3.0
npm version: 10.8.1
--- DEVICES ---
/dev/ttyUSB0
/dev/ttyACM0
--- json-live-data-server ---debug: Starting server...debug: Connect
to VBus data source...error: Main function returned with error:error:
Error: Unable to connect
    at onSocketTermination (/bin/resol-vbus/src/tcp-connection.js:368:26)
    at Socket.onError (/bin/resol-vbus/src/tcp-connection.js:401:17)
    at Socket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections
(node:internal/process/task_queues:82:21)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
--- VERSIONS ---
add-on version: 0.0.7
nodejs version: v22.3.0
npm version: 10.8.1
--- DEVICES ---
/dev/ttyUSB0
/dev/ttyACM0
--- json-live-data-server ---debug: Starting server...debug: Connect
to VBus data source...error: Main function returned with error:error:
TypeError: ConnectionClass is not a constructor
    at main (/bin/resol-vbus/examples/json-live-data-server/index.js:663:24)
    at process.processTicksAndRejections
(node:internal/process/task_queues:95:5)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
--- VERSIONS ---
add-on version: 0.0.7
nodejs version: v22.3.0
npm version: 10.8.1
--- DEVICES ---
/dev/ttyUSB0
/dev/ttyACM0
--- json-live-data-server ---debug: Starting server...debug: Connect
to VBus data source...error: Main function returned with error:error:
TypeError: ConnectionClass is not a constructor
    at main (/bin/resol-vbus/examples/json-live-data-server/index.js:663:24)
    at process.processTicksAndRejections
(node:internal/process/task_queues:95:5)


Op za 15 jun 2024 om 12:51 schreef danielwippermann <
***@***.***>:

**Comment by freddy357** [comment]
Sorry i made a type fault,

It did do it, all is working.

Thanks for the help.


Op za 15 jun 2024 om 18:43 schreef f.wing63 ***@***.***>:
