### ISSUE TITLE
Resol DL2 Lan Connection refused / not working

### ISSUE THREAD

**Issue by rblumenthal678** [danielwippermann/resol-vbus#105]
I have installed the hass-Deltasol-KM2 custom component with associated Resol-VBus json live data server addon.  The addon seems to be functioning, but I get an error indicating an incorrect password.  

Any suggestions would be helpful.  Thanks.

DL2 has remote acess enabled with the following:
   LAN MTU 1492
   HTTPS port 443
   Remote access port 7053

**configuration.yaml** has the following:
sensor:
  - platform: deltasol
    host: 127.0.0.1:3333
    username: admin
    password: abc123

**/homeasistant/addons/conf.js** has the following settings updated from default:
        host: '192.168.0.35',
        password: 'abc123',

Error log as follows:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
--- VERSIONS ---
add-on version: 0.0.7
nodejs version: v22.7.0
npm version: 10.8.2
--- DEVICES ---
ls: cannot access '/dev/ttyUSB*': No such file or directory
ls: cannot access '/dev/ttyACM*': No such file or directory
--- json-live-data-server ---
debug: Starting server...
debug: Connect to VBus data source...
debug: Starting text logging
error: Main function returned with error:
error: Error: Remote side responded with "-ERROR: Password rejected"
    at onLine (/bin/resol-vbus/src/tcp-connection.js:271:35)
    at Socket.onSocketData (/bin/resol-vbus/src/tcp-connection.js:328:33)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)

**Comment by dm82m** [comment]
@rblumenthal678 why are you using the addon? With a DL2 device you should just be fine to use the integration. See: https://github.com/dm82m/hass-Deltasol-KM2

**Comment by dm82m** [comment]
we can close this issue here and continue the discussion in https://github.com/dm82m/hass-Deltasol-KM2/issues/44
