### ISSUE TITLE
Error in the documentation

### ISSUE THREAD

**Issue by shaoran** [danielwippermann/resol-vbus#15]
For a client I had to implement a custom implementation of resol-vbus.

The client has a [TiSUN Multiplex](http://www.tisun.com/products/solar-components/solar-control-units/#multiplex-solar-control-unit), a [TiSUN Webmodule EX](http://www.tisun.com/products/solar-components/solar-control-units/#webmodule-ex) and two [Multiplex expansion modules](http://www.tisun.com/products/solar-components/solar-control-units/#multiplex-expansion-module).

Thanks to this [packet list](http://danielwippermann.github.io/resol-vbus/vbus-packets.html) I was able to decode the information my client needed. It also needed the states of the relays of the expansion modules. The tech support at TiSUN told me, that **EM #0 (0x6650) <= Broadcast (0x0000), command 0x0200** is the packet I was looking for.

However when I scanned the whole vbus, such a packet was never sent, instead there were two other packages (with targets `0x6651` and `0x6652`) that had the same structure. At first I didn't realize that these packages were the relays values and my implementation dropped them. After careful inspection I realized that these packages contained the relays values. Also the spec XML files in the resol software do not list these packages.

These two packages should be added to the documentation.

**Comment by danielwippermann** [comment]
Thanks for the feedback and filing the issue.

You are right, the titles of packets like the one you encountered are far from perfect at the moment. The title basically suggests that the section describes a packet sent from one specific address (0x0000) to another specific address (0x6650). But in truth they are more like a blueprint for packets from a range of addresses (in this case any address) to a range of addresses (0x6650 - 0x665F).

Would it have helped you if the title would have been something more along this line?

*EM (0x6650-0x665F) <= any source, command 0x0200*

I think that I could change the documentation generation to output something like this. If you have any other suggestions I'm happy to discuss them ;)

Thanks again!

**Comment by danielwippermann** [comment]
I just commited a first update to the VBus packet list in https://github.com/danielwippermann/resol-vbus/commit/8bea79b440b287c41b463387574f189e7c2548cb . It not only improves the packet titles, but fixes some incorrectly scaled factors on fields (e.g. most temperatures).

I appreciate your feedback.

**Comment by shaoran** [comment]
> Would it have helped you if the title would have been something more along this line?
>
> EM (0x6650-0x665F) <= any source, command 0x0200

Yes, that would have helped actually. I realized that the target was 0x6651 when I looked at the raw messages of the webmodule.

Thanks for updating the package list.

**Comment by danielwippermann** [comment]
I'm closing this issue for now based on your feedback. Feel free to reopen it or create a new one in case you encouter any additional problems.
