### ISSUE TITLE
[Question] Will this be updated further?

### ISSUE THREAD

**Issue by Tomson124** [danielwippermann/resol-vbus#17]
Hello,

first of all thank you for this, currently building a angularJS web dashboard for showing live data.
I noticed some warning when installing the packet as other packets are deprecated or out of date.
Will this be updated? And will you push those updates to the npm then? Or should I build it from the source here?

**Comment by danielwippermann** [comment]
I'll release a new version to the NPM registry over the weekend. I'll update this issue once it is done.

**Comment by danielwippermann** [comment]
I just released the version 0.17.0 to the NPM registry. Happy coding!
