### ISSUE TITLE
Daten von DL1 auslesen

### ISSUE THREAD

**Issue by MrIcemanLE** [danielwippermann/resol-vbus#18]
Hi @ all,

I'm currently trying to read the Data sent from the Resol DL1 which is attached to COM6 at my Windows machine. I allready tryed two different approches:
```
var vbus = require('resol-vbus');
var connection = new vbus.SerialConnection({ path: 'COM6' });
	connection.on('connectionState', function(state) {
	console.log(state);
});
connection.on('packet', function(packet) {
	console.log(packet.getId());
});
connection.on('datagram', function(datagram) {
	console.log(datagram.getId());
});
connection.connect();
```

I get es successfull connection but no packet data.
The I modified the example of the json-live-data-server example as floows:
```
var config = {
	/**
	 * The port number for the HTTP server to listen to.
	 * @type {Number}
	 */
	httpPort: 3333,
	/**
	 * The inteval in milliseconds between two writes of the logging file.
	 * @type {Number}
	 */
	loggingInterval: 10000,

	/**
	 * The filename of the logging file.
	 * @type {String}
	 */
	loggingFilename: path.resolve(__dirname, 'live-data.json'),
	/**
	 * The name of the `Connection` subclass to use for connecting to the VBus.
	 * @type {String}
	 */
	connectionClassName: 'SerialConnection',
	connectionOptions: {
		/**
		 * The host name / IP address of the VBus/LAN or Datalogger device.
		 * @type {String}
		 */
		path: 'COM6',
		/**
		 * The password for the VBus/LAN or Datalogger device.
		 * @type {String}
		 */
		password: '',
	},
};
module.exports = config;
```
But the json keeps empty. What am I doing wrong?

Normaly I use the following approach wich is working almost perfect (except of providing live data)
--> Dialup to the DL1 via Null Modem connection resulting in an IP 192.168.192.1
--> Connect the ResolServiceCenter to the IP
--> Data incomming and saving every 15 minutes to log (so far so good)

But it whould be nice to have access to the live data.

Any sugestions?

Kind Regards

**Comment by danielwippermann** [comment]
I'm sorry to say that this library does not support the DL1. The protocols used in the dial up connection to the DL1 basically require to provide a OS independent mini-PPP-LCP-IP-TCP stack which is out of scope for the resol-vbus library.

And even if you have such a stack running (either reimplemented or using the stack integrated in your OS) as far as I know the DL1 does not give you access to live data. In contrast to DL2 / DL3 / KM1 / KM2 there is no support for the VBus over TCP prototcol in the DL1 making it hard to get to the live data.

Sorry to not be of more help on this issue.
