### ISSUE TITLE
Vitosol 200

### ISSUE THREAD

**Issue by salamander-in-steinachtal** [danielwippermann/resol-vbus#19]
Excellent Code and highly useful Daniel, many thanks for providing such an amazing toolset.

Im using the vbus-proxy because it data logs ;-) and to get the app to work, however the Vitosol 200 presents itself as exactly that and not the ?MX?  product.

The app says unknown controller (all tool true).

Im not sure were would be a good place to amend the responses going to the app and also what I would need to "pretend" to be (what strings will the app accept).

Perhaps you can help me ?

**Comment by danielwippermann** [comment]
Yeah, sounds like a fun and useful extension to an optional conversion of values to another set of values that the VBusTouch application can then display on its graphics. I think I can prepare and test something over the weekend. I'll post an update once I have something to show.

**Comment by danielwippermann** [comment]
You can find the first draft of that feature in the "vbustouch-proxy" example starting with commit  7d859b0. To use it yourself you would have to follow some steps:

- start the example with the `rewriteWebHeaderSets` config option disabled
- wait a couple of seconds / minutes for the VBus information to settle
- once the information is settled a long list of value IDs and their names is printed to the console
- find the ones you are interested in for the VBusTouch app
- change the assignments starting at line 168 (https://github.com/danielwippermann/resol-vbus/blob/7d859b013650ae02b81bbbdfc36ac910ed755d92/examples/vbustouch-proxy/index.js#L168) to whatever values you want to use instead
- edit the "config.js" file to enable the `rewriteWebHeaderSets` config option
- restart the example
- try it with your app

**Comment by salamander-in-steinachtal** [comment]
Ill try it this evening, ****thank****you**** !!!!

**Comment by salamander-in-steinachtal** [comment]
specification.setPacketFieldRawValues(packetFields, {
        '00_0010_1060_10_0100_000_2_0': tempCollector,
        '00_0010_1060_10_0100_002_2_0': tempStoreBottom,
        '00_0010_1060_10_0100_004_2_0': tempStoreTop,
        '00_0010_1060_10_0100_044_1_0': pumpSpeed,
        '00_0010_1060_10_0100_045_1_0': info1,
        '00_0010_1060_10_0100_046_1_0': info2,
        '00_0010_1060_10_0100_060_2_0': errorMask,
        '00_0010_1065_10_0100_000_2_0': tempFlow,
        '00_0010_1065_10_0100_002_2_0': tempReturn,
        '00_0010_1065_10_0100_004_2_0': flow,
        '00_0010_1065_10_0100_006_2_0': heat % 1000,
        '00_0010_1065_10_0100_008_2_0': (heat / 1000) % 1000,
        '00_0010_1065_10_0100_010_2_0': heat / 1000000,
    });

Doesnt appear to work at all, still just get "Unknown controller" in the app (same as before)

rewriteWebHeaderSets: true,

changed

/*
     * Create an empty packet for the heat quantity information.
     */
    var supportedPacket2 = new vbus.Packet({
        timestamp: timestamp,
        channel: 0,
        destinationAddress: 0x0010,  // DFA
        sourceAddress: **0x1065**,  // Vitosolic 200 [WMZ1]
        command: 0x0100,
        frameCount: 3,
    });

I think mine are 1065 and 1066 (wmz1/wmz2)

**Comment by salamander-in-steinachtal** [comment]
Heres the wirshark

00000000  47 45 54 20 2f 64 6c 78  2f 64 6f 77 6e 6c 6f 61   GET /dlx /downloa
00000010  64 2f 64 6f 77 6e 6c 6f  61 64 3f 6f 75 74 70 75   d/downlo ad?outpu
00000020  74 54 79 70 65 3d 76 62  75 73 26 64 61 74 61 4c   tType=vb us&dataL
00000030  61 6e 67 75 61 67 65 3d  64 65 26 73 6f 75 72 63   anguage= de&sourc
00000040  65 3d 63 75 72 72 65 6e  74 26 73 65 73 73 69 6f   e=curren t&sessio
00000050  6e 41 75 74 68 55 73 65  72 6e 61 6d 65 3d 61 64   nAuthUse rname=ad
00000060  6d 69 6e 26 73 65 73 73  69 6f 6e 41 75 74 68 50   min&sess ionAuthP
00000070  61 73 73 77 6f 72 64 3d  76 62 75 73 20 48 54 54   assword= vbus HTT
00000080  50 2f 31 2e 31 0d 0a 48  6f 73 74 3a 20 31 39 32   P/1.1..H ost: 192
00000090  2e 31 36 38 2e 32 2e 31  30 38 3a 33 30 30 30 0d   .168.2.1 08:3000.
000000A0  0a 49 66 2d 4e 6f 6e 65  2d 4d 61 74 63 68 3a 20   .If-None -Match: 
000000B0  57 2f 22 39 65 2d 61 39  4a 34 67 63 51 62 37 41   W/"9e-a9 J4gcQb7A
000000C0  61 34 74 77 46 4c 56 6f  33 35 77 37 37 6e 43 54   a4twFLVo 35w77nCT
000000D0  34 22 0d 0a 41 63 63 65  70 74 3a 20 2a 2f 2a 0d   4"..Acce pt: */*.
000000E0  0a 55 73 65 72 2d 41 67  65 6e 74 3a 20 56 42 75   .User-Ag ent: VBu
000000F0  73 54 6f 75 63 68 2f 31  30 36 30 31 20 43 46 4e   sTouch/1 0601 CFN
00000100  65 74 77 6f 72 6b 2f 38  39 37 2e 31 35 20 44 61   etwork/8 97.15 Da
00000110  72 77 69 6e 2f 31 37 2e  35 2e 30 0d 0a 41 63 63   rwin/17. 5.0..Acc
00000120  65 70 74 2d 4c 61 6e 67  75 61 67 65 3a 20 64 65   ept-Lang uage: de
00000130  2d 64 65 0d 0a 41 63 63  65 70 74 2d 45 6e 63 6f   -de..Acc ept-Enco
00000140  64 69 6e 67 3a 20 67 7a  69 70 2c 20 64 65 66 6c   ding: gz ip, defl
00000150  61 74 65 0d 0a 43 6f 6e  6e 65 63 74 69 6f 6e 3a   ate..Con nection:
00000160  20 6b 65 65 70 2d 61 6c  69 76 65 0d 0a 0d 0a       keep-al ive....
    00000000  48 54 54 50 2f 31 2e 31  20 32 30 30 20 4f 4b 0d   HTTP/1.1  200 OK.
    00000010  0a 58 2d 50 6f 77 65 72  65 64 2d 42 79 3a 20 45   .X-Power ed-By: E
    00000020  78 70 72 65 73 73 0d 0a  63 6f 6e 74 65 6e 74 2d   xpress.. content-
    00000030  74 79 70 65 3a 20 61 70  70 6c 69 63 61 74 69 6f   type: ap plicatio
    00000040  6e 2f 6f 63 74 65 74 2d  73 74 72 65 61 6d 0d 0a   n/octet- stream..
    00000050  43 6f 6e 74 65 6e 74 2d  4c 65 6e 67 74 68 3a 20   Content- Length: 
    00000060  31 35 38 0d 0a 45 54 61  67 3a 20 57 2f 22 39 65   158..ETa g: W/"9e
    00000070  2d 49 49 71 75 4c 66 64  53 42 4c 37 4f 4d 4f 65   -IIquLfd SBL7OMOe
    00000080  79 43 57 39 53 2f 31 66  79 2f 4c 6b 22 0d 0a 44   yCW9S/1f y/Lk"..D
    00000090  61 74 65 3a 20 4d 6f 6e  2c 20 32 31 20 4d 61 79   ate: Mon , 21 May
    000000A0  20 32 30 31 38 20 31 31  3a 33 37 3a 32 34 20 47    2018 11 :37:24 G
    000000B0  4d 54 0d 0a 43 6f 6e 6e  65 63 74 69 6f 6e 3a 20   MT..Conn ection: 
    000000C0  6b 65 65 70 2d 61 6c 69  76 65 0d 0a 0d 0a a5 44   keep-ali ve.....D
    000000D0  0e 00 0e 00 91 5f 7d 82  63 01 00 00 a5 66 6a 00   ....._}. c....fj.
    000000E0  6a 00 91 5f 7d 82 63 01  00 00 10 00 60 10 10 00   j.._}.c. ....`...
    000000F0  00 01 50 00 00 00 00 00  00 00 00 00 00 00 00 00   ..P..... ........
    00000100  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
    00000110  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
    00000120  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
    00000130  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
    00000140  00 00 00 00 00 00 a5 66  26 00 26 00 91 5f 7d 82   .......f &.&.._}.
    00000150  63 01 00 00 10 00 65 10  10 00 00 01 0c 00 00 00   c.....e. ........
    00000160  00 00 00 00 00 00 00 00  00 00 00 00               ........ ....
0000016F  47 45 54 20 2f 64 6c 78  2f 64 6f 77 6e 6c 6f 61   GET /dlx /downloa
0000017F  64 2f 64 6f 77 6e 6c 6f  61 64 3f 6f 75 74 70 75   d/downlo ad?outpu
0000018F  74 54 79 70 65 3d 76 62  75 73 26 64 61 74 61 4c   tType=vb us&dataL
0000019F  61 6e 67 75 61 67 65 3d  64 65 26 73 6f 75 72 63   anguage= de&sourc
000001AF  65 3d 63 75 72 72 65 6e  74 26 73 65 73 73 69 6f   e=curren t&sessio
000001BF  6e 41 75 74 68 55 73 65  72 6e 61 6d 65 3d 61 64   nAuthUse rname=ad
000001CF  6d 69 6e 26 73 65 73 73  69 6f 6e 41 75 74 68 50   min&sess ionAuthP
000001DF  61 73 73 77 6f 72 64 3d  76 62 75 73 20 48 54 54   assword= vbus HTT
000001EF  50 2f 31 2e 31 0d 0a 48  6f 73 74 3a 20 31 39 32   P/1.1..H ost: 192
000001FF  2e 31 36 38 2e 32 2e 31  30 38 3a 33 30 30 30 0d   .168.2.1 08:3000.
0000020F  0a 49 66 2d 4e 6f 6e 65  2d 4d 61 74 63 68 3a 20   .If-None -Match: 
0000021F  57 2f 22 39 65 2d 49 49  71 75 4c 66 64 53 42 4c   W/"9e-II quLfdSBL
0000022F  37 4f 4d 4f 65 79 43 57  39 53 2f 31 66 79 2f 4c   7OMOeyCW 9S/1fy/L
0000023F  6b 22 0d 0a 41 63 63 65  70 74 3a 20 2a 2f 2a 0d   k"..Acce pt: */*.
0000024F  0a 55 73 65 72 2d 41 67  65 6e 74 3a 20 56 42 75   .User-Ag ent: VBu
0000025F  73 54 6f 75 63 68 2f 31  30 36 30 31 20 43 46 4e   sTouch/1 0601 CFN
0000026F  65 74 77 6f 72 6b 2f 38  39 37 2e 31 35 20 44 61   etwork/8 97.15 Da
0000027F  72 77 69 6e 2f 31 37 2e  35 2e 30 0d 0a 41 63 63   rwin/17. 5.0..Acc
0000028F  65 70 74 2d 4c 61 6e 67  75 61 67 65 3a 20 64 65   ept-Lang uage: de
0000029F  2d 64 65 0d 0a 41 63 63  65 70 74 2d 45 6e 63 6f   -de..Acc ept-Enco
000002AF  64 69 6e 67 3a 20 67 7a  69 70 2c 20 64 65 66 6c   ding: gz ip, defl
000002BF  61 74 65 0d 0a 43 6f 6e  6e 65 63 74 69 6f 6e 3a   ate..Con nection:
000002CF  20 6b 65 65 70 2d 61 6c  69 76 65 0d 0a 0d 0a       keep-al ive....
    0000016C  48 54 54 50 2f 31 2e 31  20 32 30 30 20 4f 4b 0d   HTTP/1.1  200 OK.
    0000017C  0a 58 2d 50 6f 77 65 72  65 64 2d 42 79 3a 20 45   .X-Power ed-By: E
    0000018C  78 70 72 65 73 73 0d 0a  63 6f 6e 74 65 6e 74 2d   xpress.. content-
    0000019C  74 79 70 65 3a 20 61 70  70 6c 69 63 61 74 69 6f   type: ap plicatio
    000001AC  6e 2f 6f 63 74 65 74 2d  73 74 72 65 61 6d 0d 0a   n/octet- stream..
    000001BC  43 6f 6e 74 65 6e 74 2d  4c 65 6e 67 74 68 3a 20   Content- Length: 
    000001CC  31 35 38 0d 0a 45 54 61  67 3a 20 57 2f 22 39 65   158..ETa g: W/"9e
    000001DC  2d 55 41 37 59 75 72 58  47 6a 39 67 73 6c 6b 6a   -UA7YurX Gj9gslkj
    000001EC  52 76 66 39 51 45 43 67  6f 75 63 55 22 0d 0a 44   Rvf9QECg oucU"..D
    000001FC  61 74 65 3a 20 4d 6f 6e  2c 20 32 31 20 4d 61 79   ate: Mon , 21 May
    0000020C  20 32 30 31 38 20 31 31  3a 33 37 3a 32 36 20 47    2018 11 :37:26 G
    0000021C  4d 54 0d 0a 43 6f 6e 6e  65 63 74 69 6f 6e 3a 20   MT..Conn ection: 
    0000022C  6b 65 65 70 2d 61 6c 69  76 65 0d 0a 0d 0a a5 44   keep-ali ve.....D
    0000023C  0e 00 0e 00 b3 62 7d 82  63 01 00 00 a5 66 6a 00   .....b}. c....fj.
    0000024C  6a 00 b3 62 7d 82 63 01  00 00 10 00 60 10 10 00   j..b}.c. ....`...
    0000025C  00 01 50 00 00 00 00 00  00 00 00 00 00 00 00 00   ..P..... ........
    0000026C  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
    0000027C  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
    0000028C  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
    0000029C  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
    000002AC  00 00 00 00 00 00 a5 66  26 00 26 00 b3 62 7d 82   .......f &.&..b}.
    000002BC  63 01 00 00 10 00 65 10  10 00 00 01 0c 00 00 00   c.....e. ........
    000002CC  00 00 00 00 00 00 00 00  00 00 00 00               ........ ....

**Comment by danielwippermann** [comment]
It took me a while to realize that the iPad app (which I tested with) and the iPhone app have a different set of controllers they support... I have committed a couple of changes to the example (see  3b27a11 for details). Please try it again, it should now work on the iPhone as well.

**Comment by salamander-in-steinachtal** [comment]
Many thanks - that's great now I can see values on the iPhone App too.
