### ISSUE TITLE
VBUS with just a usb ftdi connector?

### ISSUE THREAD

**Issue by wuftymerguftyguff** [danielwippermann/resol-vbus#23]
Hi,

Not an issue, just a question

Do I need additional hardware like a datalogger or resol proprietary usb interface to use this? or can I connect a usb rs232 or RS485  serial port to the vbus connections? 

Thanks for all your work.

**Comment by danielwippermann** [comment]
Hi,

the VBus signal differ from standard RS232 and RS485 signal specifications (see the VBus spec for details and a sample circuitry at the bottom of the page: http://danielwippermann.github.io/resol-vbus/vbus-specification.html).

That said: I have heard feedback from several users that use RS485 adapters to receive (not send) VBus data. So it might work, but there is no guarantee...

Best regards,
Daniel
