### ISSUE TITLE
whet nodejs version supported ?

### ISSUE THREAD

**Issue by faronov** [danielwippermann/resol-vbus#26]
I try multiple different version of nodejs
have lot of problem with npm install
anyway when I try execute examples it fails on mostly every line :( 
can you recommend nodejs version that will work with this examples
I try run vbustouch-proxy

**Comment by danielwippermann** [comment]
I'm using Node v10.15.1 on my development machine currently. The library itself is automatically tested against Node v6, v8, v10 and stable (which was v11.9.0 when the tests last ran) using Travis CI. So any of them should work...

If you want me to recommend a version I would prefer the latest long-term-support release which is v10.15.2 as of this writing.

I just updated my dev machine to that version as well, did a clean checkout of this repo, followed the instructions in the example to setup it up and got it running without errors.

Could you please provide a copy of one of the errors you are experiencing?

**Comment by faronov** [comment]
I try use raspberry pi 3 with serial port communication  for that purposes , I will reinstall everything from scratch, and will try again with lates 10.15 NodeJS , and let you know if I will have issues with installation and using examples.
For now I made so many tries with so many difference versions of NodeJS, and may broke something.

**Comment by faronov** [comment]
Sorry, I really messed something in the system, that screwed all set up :)
everything it works like a charm 
thanks for this great project.

**Comment by danielwippermann** [comment]
Thanks for the feedback! Happy hacking :)
