### ISSUE TITLE
json-live-data-server not updating values

### ISSUE THREAD

**Issue by bwesemann** [danielwippermann/resol-vbus#27]
hi,

i dont know if the problem is on vbus side or on json-live-data-server. i have two resol, one 5611 and 2271. i am monitoring with grafana and sometimes i see that the values arent updated for some period. if i curl i get the same values, they are not updatet:

root@stony2:~/resol-vbus/examples/json-live-data-server# curl -s http://127.0.0.1:3333/api/v1/live-data
[
    {
        "id": "00_0010_2271_10_0100_000_4_0",
        "name": "System date",
        "rawValue": 582795724
    },
    {
        "id": "00_0010_2271_10_0100_004_2_0",
        "name": "Temperature sensor 1",
        "rawValue": 60
    },
    {
        "id": "00_0010_2271_10_0100_006_2_0",
        "name": "Temperature sensor 2",
        "rawValue": 58.5
    },
    {
        "id": "00_0010_2271_10_0100_008_2_0",
        "name": "Temperature sensor 3",
        "rawValue": 50.5
    },
    {
        "id": "00_0010_2271_10_0100_010_2_0",
        "name": "Temperature sensor 4",
        "rawValue": 56
    },
    {
        "id": "00_0010_2271_10_0100_012_2_0",
        "name": "TAGE",
        "rawValue": 881
    },
    {
        "id": "00_0010_2271_10_0100_016_4_0",
        "name": "Flow rate V40",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_020_1_0",
        "name": "Pump speed relay 1",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_021_1_0",
        "name": "Pump speed relay 2",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_022_1_0",
        "name": "Pump speed relay 4",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_024_4_0",
        "name": "Heat quantity",
        "rawValue": 88177
    },
    {
        "id": "00_0010_2271_10_0100_028_2_0",
        "name": "SW Version",
        "rawValue": 1.04
    },
    {
        "id": "00_0010_2271_10_0100_032_4_0",
        "name": "Operating hours relay 1",
        "rawValue": 54
    },
    {
        "id": "00_0010_2271_10_0100_036_4_0",
        "name": "Operating hours relay 2",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_040_4_0",
        "name": "Operating hours relay 3",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_044_1_1",
        "name": "Holiday function",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_045_1_0",
        "name": "Blocking protection 1",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_046_1_0",
        "name": "Blocking protection 2",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_047_1_0",
        "name": "Blocking protection 3",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_048_4_0",
        "name": "Initialise",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_052_4_0",
        "name": "Filling",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_054_4_0",
        "name": "Stabilise",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_060_1_0",
        "name": "Pump delay",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_061_1_1",
        "name": "Heat dump",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_062_1_0",
        "name": "Overrun",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_063_1_0",
        "name": "Thermal disinfection",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_064_1_1",
        "name": "Store cooling",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_065_1_1",
        "name": "System cooling",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_066_1_0",
        "name": "Spreading",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_067_1_0",
        "name": "Antifreeze",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_068_1_1",
        "name": "Collector cooling",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_069_1_1",
        "name": "Maximum store temperature",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_070_1_1",
        "name": "Restarts",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_072_4_0",
        "name": "Error mask",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_072_1_1",
        "name": "Error: Sensor fault",
        "rawValue": 0
    },
    {
        "id": "00_0010_2272_10_0100_000_4_0",
        "name": "Value",
        "rawValue": 88676
    },
    {
        "id": "00_0010_2272_10_0100_004_4_0",
        "name": "Power",
        "rawValue": 0
    },
    {
        "id": "00_0010_2272_10_0100_008_4_0",
        "name": "Value today",
        "rawValue": 733
    },
    {
        "id": "00_0010_2272_10_0100_012_4_0",
        "name": "Value week",
        "rawValue": 75458
    },
    {
        "id": "00_0010_5611_10_0100_000_2_0",
        "name": "Temperature sensor 1",
        "rawValue": 27.200000000000003
    },
    {
        "id": "00_0010_5611_10_0100_002_2_0",
        "name": "Temperature sensor 2",
        "rawValue": 59.800000000000004
    },
    {
        "id": "00_0010_5611_10_0100_004_2_0",
        "name": "Temperature sensor 3",
        "rawValue": 61.6
    },
    {
        "id": "00_0010_5611_10_0100_006_2_0",
        "name": "Temperature sensor 4",
        "rawValue": 25.6
    },
    {
        "id": "00_0010_5611_10_0100_008_1_0",
        "name": "Pump speed relay 1",
        "rawValue": 0
    },
    {
        "id": "00_0010_5611_10_0100_009_1_0",
        "name": "Pump speed relay 2",
        "rawValue": 100
    },
    {
        "id": "00_0010_5611_10_0100_010_1_0",
        "name": "Mixer open",
        "rawValue": 0
    },
    {
        "id": "00_0010_5611_10_0100_011_1_0",
        "name": "Mixer closed",
        "rawValue": 0
    },
    {
        "id": "00_0010_5611_10_0100_018_1_0",
        "name": "System message",
        "rawValue": 0
    },
    {
        "id": "00_0010_5611_10_0100_012_4_0",
        "name": "Date",
        "rawValue": 20190621
    },
    {
        "id": "00_0010_5611_10_0100_016_2_0",
        "name": "Time",
        "rawValue": 514
    }
]root@stony2:~/resol-vbus/examples/json-live-data-server# curl -s http://127.0.0.1:3333/api/v1/live-data
[
    {
        "id": "00_0010_2271_10_0100_000_4_0",
        "name": "System date",
        "rawValue": 582795724
    },
    {
        "id": "00_0010_2271_10_0100_004_2_0",
        "name": "Temperature sensor 1",
        "rawValue": 60
    },
    {
        "id": "00_0010_2271_10_0100_006_2_0",
        "name": "Temperature sensor 2",
        "rawValue": 58.5
    },
    {
        "id": "00_0010_2271_10_0100_008_2_0",
        "name": "Temperature sensor 3",
        "rawValue": 50.5
    },
    {
        "id": "00_0010_2271_10_0100_010_2_0",
        "name": "Temperature sensor 4",
        "rawValue": 56
    },
    {
        "id": "00_0010_2271_10_0100_012_2_0",
        "name": "TAGE",
        "rawValue": 881
    },
    {
        "id": "00_0010_2271_10_0100_016_4_0",
        "name": "Flow rate V40",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_020_1_0",
        "name": "Pump speed relay 1",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_021_1_0",
        "name": "Pump speed relay 2",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_022_1_0",
        "name": "Pump speed relay 4",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_024_4_0",
        "name": "Heat quantity",
        "rawValue": 88177
    },
    {
        "id": "00_0010_2271_10_0100_028_2_0",
        "name": "SW Version",
        "rawValue": 1.04
    },
    {
        "id": "00_0010_2271_10_0100_032_4_0",
        "name": "Operating hours relay 1",
        "rawValue": 54
    },
    {
        "id": "00_0010_2271_10_0100_036_4_0",
        "name": "Operating hours relay 2",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_040_4_0",
        "name": "Operating hours relay 3",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_044_1_1",
        "name": "Holiday function",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_045_1_0",
        "name": "Blocking protection 1",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_046_1_0",
        "name": "Blocking protection 2",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_047_1_0",
        "name": "Blocking protection 3",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_048_4_0",
        "name": "Initialise",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_052_4_0",
        "name": "Filling",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_054_4_0",
        "name": "Stabilise",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_060_1_0",
        "name": "Pump delay",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_061_1_1",
        "name": "Heat dump",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_062_1_0",
        "name": "Overrun",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_063_1_0",
        "name": "Thermal disinfection",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_064_1_1",
        "name": "Store cooling",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_065_1_1",
        "name": "System cooling",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_066_1_0",
        "name": "Spreading",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_067_1_0",
        "name": "Antifreeze",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_068_1_1",
        "name": "Collector cooling",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_069_1_1",
        "name": "Maximum store temperature",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_070_1_1",
        "name": "Restarts",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_072_4_0",
        "name": "Error mask",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_072_1_1",
        "name": "Error: Sensor fault",
        "rawValue": 0
    },
    {
        "id": "00_0010_2272_10_0100_000_4_0",
        "name": "Value",
        "rawValue": 88676
    },
    {
        "id": "00_0010_2272_10_0100_004_4_0",
        "name": "Power",
        "rawValue": 0
    },
    {
        "id": "00_0010_2272_10_0100_008_4_0",
        "name": "Value today",
        "rawValue": 733
    },
    {
        "id": "00_0010_2272_10_0100_012_4_0",
        "name": "Value week",
        "rawValue": 75458
    },
    {
        "id": "00_0010_5611_10_0100_000_2_0",
        "name": "Temperature sensor 1",
        "rawValue": 27.200000000000003
    },
    {
        "id": "00_0010_5611_10_0100_002_2_0",
        "name": "Temperature sensor 2",
        "rawValue": 59.800000000000004
    },
    {
        "id": "00_0010_5611_10_0100_004_2_0",
        "name": "Temperature sensor 3",
        "rawValue": 61.6
    },
    {
        "id": "00_0010_5611_10_0100_006_2_0",
        "name": "Temperature sensor 4",
        "rawValue": 25.6
    },
    {
        "id": "00_0010_5611_10_0100_008_1_0",
        "name": "Pump speed relay 1",
        "rawValue": 0
    },
    {
        "id": "00_0010_5611_10_0100_009_1_0",
        "name": "Pump speed relay 2",
        "rawValue": 100
    },
    {
        "id": "00_0010_5611_10_0100_010_1_0",
        "name": "Mixer open",
        "rawValue": 0
    },
    {
        "id": "00_0010_5611_10_0100_011_1_0",
        "name": "Mixer closed",
        "rawValue": 0
    },
    {
        "id": "00_0010_5611_10_0100_018_1_0",
        "name": "System message",
        "rawValue": 0
    },
    {
        "id": "00_0010_5611_10_0100_012_4_0",
        "name": "Date",
        "rawValue": 20190621
    },
    {
        "id": "00_0010_5611_10_0100_016_2_0",
        "name": "Time",
        "rawValue": 514
    }
]root@stony2:~/resol-vbus/examples/json-live-data-server# curl -s http://127.0.0.1:3333/api/v1/live-data
[
    {
        "id": "00_0010_2271_10_0100_000_4_0",
        "name": "System date",
        "rawValue": 582795724
    },
    {
        "id": "00_0010_2271_10_0100_004_2_0",
        "name": "Temperature sensor 1",
        "rawValue": 60
    },
    {
        "id": "00_0010_2271_10_0100_006_2_0",
        "name": "Temperature sensor 2",
        "rawValue": 58.5
    },
    {
        "id": "00_0010_2271_10_0100_008_2_0",
        "name": "Temperature sensor 3",
        "rawValue": 50.5
    },
    {
        "id": "00_0010_2271_10_0100_010_2_0",
        "name": "Temperature sensor 4",
        "rawValue": 56
    },
    {
        "id": "00_0010_2271_10_0100_012_2_0",
        "name": "TAGE",
        "rawValue": 881
    },
    {
        "id": "00_0010_2271_10_0100_016_4_0",
        "name": "Flow rate V40",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_020_1_0",
        "name": "Pump speed relay 1",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_021_1_0",
        "name": "Pump speed relay 2",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_022_1_0",
        "name": "Pump speed relay 4",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_024_4_0",
        "name": "Heat quantity",
        "rawValue": 88177
    },
    {
        "id": "00_0010_2271_10_0100_028_2_0",
        "name": "SW Version",
        "rawValue": 1.04
    },
    {
        "id": "00_0010_2271_10_0100_032_4_0",
        "name": "Operating hours relay 1",
        "rawValue": 54
    },
    {
        "id": "00_0010_2271_10_0100_036_4_0",
        "name": "Operating hours relay 2",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_040_4_0",
        "name": "Operating hours relay 3",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_044_1_1",
        "name": "Holiday function",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_045_1_0",
        "name": "Blocking protection 1",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_046_1_0",
        "name": "Blocking protection 2",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_047_1_0",
        "name": "Blocking protection 3",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_048_4_0",
        "name": "Initialise",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_052_4_0",
        "name": "Filling",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_054_4_0",
        "name": "Stabilise",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_060_1_0",
        "name": "Pump delay",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_061_1_1",
        "name": "Heat dump",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_062_1_0",
        "name": "Overrun",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_063_1_0",
        "name": "Thermal disinfection",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_064_1_1",
        "name": "Store cooling",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_065_1_1",
        "name": "System cooling",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_066_1_0",
        "name": "Spreading",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_067_1_0",
        "name": "Antifreeze",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_068_1_1",
        "name": "Collector cooling",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_069_1_1",
        "name": "Maximum store temperature",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_070_1_1",
        "name": "Restarts",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_072_4_0",
        "name": "Error mask",
        "rawValue": 0
    },
    {
        "id": "00_0010_2271_10_0100_072_1_1",
        "name": "Error: Sensor fault",
        "rawValue": 0
    },
    {
        "id": "00_0010_2272_10_0100_000_4_0",
        "name": "Value",
        "rawValue": 88676
    },
    {
        "id": "00_0010_2272_10_0100_004_4_0",
        "name": "Power",
        "rawValue": 0
    },
    {
        "id": "00_0010_2272_10_0100_008_4_0",
        "name": "Value today",
        "rawValue": 733
    },
    {
        "id": "00_0010_2272_10_0100_012_4_0",
        "name": "Value week",
        "rawValue": 75458
    },
    {
        "id": "00_0010_5611_10_0100_000_2_0",
        "name": "Temperature sensor 1",
        "rawValue": 27.200000000000003
    },
    {
        "id": "00_0010_5611_10_0100_002_2_0",
        "name": "Temperature sensor 2",
        "rawValue": 59.800000000000004
    },
    {
        "id": "00_0010_5611_10_0100_004_2_0",
        "name": "Temperature sensor 3",
        "rawValue": 61.6
    },
    {
        "id": "00_0010_5611_10_0100_006_2_0",
        "name": "Temperature sensor 4",
        "rawValue": 25.6
    },
    {
        "id": "00_0010_5611_10_0100_008_1_0",
        "name": "Pump speed relay 1",
        "rawValue": 0
    },
    {
        "id": "00_0010_5611_10_0100_009_1_0",
        "name": "Pump speed relay 2",
        "rawValue": 100
    },
    {
        "id": "00_0010_5611_10_0100_010_1_0",
        "name": "Mixer open",
        "rawValue": 0
    },
    {
        "id": "00_0010_5611_10_0100_011_1_0",
        "name": "Mixer closed",
        "rawValue": 0
    },
    {
        "id": "00_0010_5611_10_0100_018_1_0",
        "name": "System message",
        "rawValue": 0
    },
    {
        "id": "00_0010_5611_10_0100_012_4_0",
        "name": "Date",
        "rawValue": 20190621
    },
    {
        "id": "00_0010_5611_10_0100_016_2_0",
        "name": "Time",
        "rawValue": 514
    }
]root@stony2:~/resol-vbus/examples/json-live-data-server# 

after some time everything is working fine 

do you have a idea how to debug this? 

best regards
ben

**Comment by danielwippermann** [comment]
Hi Ben,

both your devices - the DeltaSol SLL and the DeltaTherm FK - are VBus masters. Since the VBus is designed to be a single-master bus you should not connect multiple masters together.

Both devices send their data on a regular interval (normally once per second). I assume that if the two devices send at the same time, they corrupt each other's data resulting in values not updating for some time. Once the two devices' communication timers drift apart enough, they can manage to send their respective data without colliding with the other device. That is when data can be received by the json-live-data-server. But as the timer drift further, they will get to the collision scenario again and repeat the whole cycle.

It is best to treat the two devices as individual VBuses, using one VBus adapter per device to not have the collision problem.

I hope that answer and description helps. If you have any further questions, don't hesitate to reply here.

Best regards,
Daniel

**Comment by bwesemann** [comment]
hi daniel,

not the answer i expected, but yeah that was the problem. i thought that i can have more than one device on the vbus.

thank you so much.
best regards
ben
