### ISSUE TITLE
Protocol version 3.x VFD/RPD-Sensoren

### ISSUE THREAD

**Issue by andistgt72** [danielwippermann/resol-vbus#30]
Guten Tag,
 
Ich suche eine genauere Beschreibung des Protokolls Version 3.x für die VFD und RPD Sensoren. Leider kann ich zu den gesendeten Daten der Sensoren keine genaue Beschreibung finden. Ich würde gerne die Daten der Sensoren über den VBus auslesen und interpretieren können (ohne zusätzlichen Regler). Können Sie mir da vielleicht weiter helfen? Für eine Unterstützung bedanke ich mich schon im voraus.
 
Grüßen
 
Andreas

**Comment by danielwippermann** [comment]
Closing this issue since the question has been answered outside of the issue tracker.
