### ISSUE TITLE
Resol with Home assistant

### ISSUE THREAD

**Issue by Boosmoo** [danielwippermann/resol-vbus#33]
Hello Daniel,

Do you know if its possible to connect a resol dl2 datalogger with homeassistant?

Greetings,
Klaas

**Comment by danielwippermann** [comment]
Hi Klaas,

no, sorry, I'm not aware of any Homeassistant-related solutions.

Best regards,
Daniel

**Comment by dm82m** [comment]
@Boosmoo I will dig into that topic soon. Ordered a resol KM2 today. My plan is to use it within vbus.net and then use HomeAssistant to grab specific data from vbus.net - I know that is not exactly your scenario but maybe it could help you somehow.

**Comment by ploppythekangaroo** [comment]
Did anyone have any luck in connecting this to Home assistant?
I have a Resol LAN adapter.  I can get the data from the network to my (win10) PC, but am not sure how to get this onto my HA pi4.

**Comment by dm82m** [comment]
I am using a Resol KM2 and reading data from that adapter and putting the data into Home Assistant. If that is what you need, just let me know and I will share my solution with you.

**Comment by ploppythekangaroo** [comment]
The KM2 is different to the LAN adapter.  The Land adapter just shares the Resol (BS Plus) controller onto my local network.  I understand the KM2 shares the data to the internet for retrievable via the VBus interface.
Would love to hear if you got the data locally, or from the internet interface.
Really would like to get this working onto HA so I can monitor my Solar panels.  Wish I'd got the KM2 now!

**Comment by dm82m** [comment]
I am getting the data locally - not from vbus.net! I use this service for it: http://192.168.178.15/cgi-bin/resol-webservice maybe you can just check if the LAN adapter also provides that endpoint, I have no idea if that is the case...

**Comment by ploppythekangaroo** [comment]
All I get from that URL is a (more or less) blank page:
![Annotation 2020-09-16 091331](https://user-images.githubusercontent.com/67808381/93310878-3bc87180-f7fd-11ea-880f-0277546df854.jpg)
The page source gives nothing away.

I've managed to set up the Resol Service centre with a graphic and some live readings, but it looks like I need a DL2 or DL3 to show this elsewhere:
![Screenshot 2020-09-16 091400](https://user-images.githubusercontent.com/67808381/93311096-73cfb480-f7fd-11ea-970e-d898390bad6d.jpg)

**Comment by artspe** [comment]
@dm82m Would be interested in your solution as I'm also on KM2 and struggling to integrate it into homeassistant.

**Comment by dm82m** [comment]
@artspe added something for you here: https://github.com/dm82m/homeassistant-resol-km2

Open an issue there if you need support.

**Comment by danielwippermann** [comment]
Closing this stale issue. If you need additional help don't hesitate to open a new issue.

**Comment by dm82m** [comment]
I created a whole plugin for Home Assistant, integrated in HACS, feel free to use it: https://github.com/dm82m/hass-Deltasol-KM2
