### ISSUE TITLE
Kudos for providing the resol-vbus JS-library

### ISSUE THREAD

**Issue by pdbjjens** [danielwippermann/resol-vbus#38]
This is not to report an issue but rather to give kudos to you, Daniel @danielwippermann 
for your brilliant and continuing work to provide an easy access tool for Resol VBus devices
to the community. 
It made putting together a VBus Adapter for   **ioBroker**  [https://github.com/ioBroker](https://github.com/ioBroker) 
really simple. 
So, thanks once again for your high-quality resol-vbus library - and keep up the good work.
Best Regards
@pdbjjens

**Comment by danielwippermann** [comment]
Thank you for your kind words, I really appreciate it!

Stay safe and healthy!
Daniel
