### ISSUE TITLE
Thank you very much for your work!

### ISSUE THREAD

**Issue by ppernias** [danielwippermann/resol-vbus#39]
Thanks for your work. I've installed a raspberry pi with your code, accessing to a km2 module connected to an old deltasol M.
Then, in my HA,  I've created a REST sensor and and a platform sensor vinculated to it and finally I've got deltasol regulator values in my dashboard. 
Thanks a lot!
![Captura de pantalla 2020-06-13 a las 19 55 54](https://user-images.githubusercontent.com/6562572/84575882-dbb2d100-adb0-11ea-95b3-67fb10ae2593.png)

**Comment by danielwippermann** [comment]
Although very late, but better late than never: thanks for sharing your solution, glad it worked out!

Stay safe and healthy!
Daniel
