### ISSUE TITLE
FYI: Node sample to get vbus data into openhab, HomeAssistant, Node-RED with the help of MQTT-Homie

### ISSUE THREAD

**Issue by BenniG82** [danielwippermann/resol-vbus#48]
Hi Folks,

if somebody is interested in getting vbus data to openhab, HomeAssistant and Node-RED, take a look at my sample:
https://github.com/BenniG82/vbus-to-homie
It uses this nice lib and provides the data in a [Homie](https://homieiot.github.io/specification/) structure in your MQTT-Server.
openhab, HomeAssistant and Node-RED should now be able to easily access this data. I'm only using openhab, but the Homie-website says that HomeAssistant and Node-RED also support their spec.

@Daniel if you don't like this "advertisement", feel free to close/delete the issue :)

Have fun and stay healthy
Benjamin

**Comment by danielwippermann** [comment]
Hi Benjamin,

thanks for that link.

Would you mind if I create a section in the README and add your link there more permanently? This way I could close this issue, but people would still be able to find your solution easily.

Best regards,
Daniel

**Comment by BenniG82** [comment]
Hi Daniel,

it would be an honor if you would link my project.

Thanks and best regards
Benjamin

**Comment by danielwippermann** [comment]
Done, thanks again!

Have a happy new year and stay safe and healthy!
Daniel
