### ISSUE TITLE
Disable logging file

### ISSUE THREAD

**Issue by bigfeetneedbigboots** [danielwippermann/resol-vbus#49]
Hi Daniel

Firstly, thank you so much for your work and contribution. Kudos to you!

I'm using the json-live-data-server and don't want to write the logging file because I am looking to reduce the number of writes to the SD card of my Pi. I only want to make the json available via http where I retrieve it and consume it. I've tried commenting out the loggingFilename which works but throws "error: undefined" when the process runs. Is there currently a "clean" way to achieve this? 

Thanks again

Jason

**Comment by danielwippermann** [comment]
Hi Jason,

sorry for the delay.

I just committed (3083b6b2855ef1be3fc363a782cd66917bf5d182) a change to the json-live-data-server example that make the file-based logging optional. So you should no longer get the error messages you encountered.

Happy new year and stay healthy!
Daniel

**Comment by bigfeetneedbigboots** [comment]
Hey Daniel

Thanks for coming back to me and thanks even more for the enhancement!

Happy new year to you too mate!

Jason
