### ISSUE TITLE
rpt-files folder does not exist

### ISSUE THREAD

**Issue by nelsonzheng** [danielwippermann/resol-vbus#6]
The 'rpt-files' directory mentioned on [line 189](https://github.com/danielwippermann/resol-vbus/blob/master/examples/configuration-importer/index.js#L189) of the configuration-importer example does not exist

**Comment by danielwippermann** [comment]
Thanks for the hint. I'll write a short README for that tool to explain where to get those files from.

It basically boils down to:

- Create a new directory `.../resol-vbus/examples/configuration-importer/rpt-files`
- Download a current version of the RESOL Parameterization Tool (RPT) from RESOL's homepage
- Extract the Setup.exe using 7z (or simply install it if you use Windows) to get access to the contained files
- Copy the needed `<controller>-Menu.xml` files from the RPT directory to the `rpt-files` directory
- Edit the `main` function in the `index.js` to only process the files you are interested in

**Comment by danielwippermann** [comment]
I have uploaded a README for the tool under https://github.com/danielwippermann/resol-vbus/blob/master/examples/configuration-importer/README.md . I close this issue for now. Feel free to reopen it or create a new one if you need more information.
