### ISSUE TITLE
VBus/LAN not connecting properly

### ISSUE THREAD

**Issue by BernieHoll** [danielwippermann/resol-vbus#61]
Hi,
I'm trying to get data into my home automation system from my DeltaSol BS/2 via a VBus/LAN but I'm not getting a connection.

I have the VBus/LAN and DeltaSol BS2 setup and working.
I can connect to the VBus/LAN with RSC and see valid data and its updating.
Running on a Windows 10 64bit machine and the VBus/LAN is firmware V2.0.

I tried to Telnet to the VBus/LAN and get the folloing issue.
It seems to half process and then falls over :(
![Capture](https://user-images.githubusercontent.com/87884868/126854430-61b0c6fb-63b6-40d7-a451-b6493b0ecf66.JPG)

Any help would be appreciated.

Bernie

**Comment by danielwippermann** [comment]
Closing this stale issue. If you still have trouble connecting to your VBus/LAN please try an updated version of this library and create a new issue if necessary.

Thanks, Daniel
