### ISSUE TITLE
Openhab Resol Binding with Citrin SLR

### ISSUE THREAD

**Issue by Jochen-K** [danielwippermann/resol-vbus#64]
Hi there,

I installed Openhab 3.1 with Resol Binding on a Raspberry Pi 4. For the connection to the Citrin SLR heating control, I have a Resol KM2. The integration of the KM2 and the Citrin SLR in Openhab works without any problems.
Unfortunately, the values are only transferred once (when integrating, or after restarting the KM2). I also don't know whether all values will be transferred.
For information: The values are updated again and again on vbus.net and the binding also works perfectly under openHAB 2.5.
Unfortunately I saw that my Citrine SLR is not on the list of compatible devices, maybe that's my problem.

Could it be possible to add my device?

Best regards
Yokes

PS: The translation into English was done by Google :-)

**Comment by danielwippermann** [comment]
I'll close this issue due to inactivity. If the problem is still relevant, consider re-opening it in the OpenHAB addon repo instead to get in touch with its developer directly.

Best regards,
Daniel
