### ISSUE TITLE
Missing example file for use em example

### ISSUE THREAD

**Issue by tiele** [danielwippermann/resol-vbus#65]

**Comment by danielwippermann** [comment]
If you are refering to the state file the home automation system should write to: it is assumed to be a single-line text file containing either "0", "off" or "aus" for the switch-off case or "1", "on", "ein" for the switch-on case.

If you plan to extend that list, you can find the corresponding code here: https://github.com/danielwippermann/resol-vbus/blob/9a4b22aec0fe0cb0d94710f11eb5e26ea15ce3ef/examples/em-simulator/main.js#L58

I'll put that in the README as well.

**Comment by tiele** [comment]
thank you for your feedback. I discovered along the way that my controller (BX) doesn't support the EM module. Pity, but i seem to have an alternative in overwriting parameters in the controller (in reasonable amounts)...
