### ISSUE TITLE
Does DeltasolMX broadcast frames/packets with calculated temperatures from EMs' inputs?

### ISSUE THREAD

**Issue by adliner** [danielwippermann/resol-vbus#66]
Hi,
does DeltasolMX broadcast frames/packets with calculated temperatures from EMs' inputs? EMs broadcasts packets containing resistance measured on their inputs. Based on the knowledge what kind of sensor (PT100, PT1000 etc) is connected to the corresponding input it is possible to calculate the measured temperature but does DeltasolMX also broadcast any packet with already calculated temperature?

Edit: I found a doc for this packet: http://danielwippermann.github.io/resol-vbus/#/vsf/fields/00_0010_1161_10_0100 but not sure what is 'MFR' device that broadcasts this. This packet looks like what I'm loking for:  http://danielwippermann.github.io/resol-vbus/#/vsf/fields/00_0010_7E12_10_0100 , it seems to be broadcasted by DeltasolMX controller, but is it supported in all firmware versions ( originally DeltasolMX seemed to have device address: 0x7E11 while this packet mentions 0x7E12 referring to the same device )?

Thanks,
Adam

**Comment by danielwippermann** [comment]
Hi Adam,

yes, the 0x7e12 is also sent by the MX. Depending on you firmware version you either get the packet you mentioned or (I think on later firmware versions) individual packets per activated module: http://danielwippermann.github.io/resol-vbus/#/vsf/fields/00_0010_7E40_10_0100

Best regards,
Daniel
