### ISSUE TITLE
Wrong Password

### ISSUE THREAD

**Issue by lapixo** [danielwippermann/resol-vbus#67]
Hi,
i start the example but got an error with my KM2 Module.

~/resol-vbus/examples/json-live-data-server $ node index.js
debug: Starting server...
debug: Connect to VBus data source...
error: undefined {"vbusPhase":"PASS"}

In the config i have set the correct IP of my KM2 and the password which i got/set from here:
![Bildschirmfoto 2022-01-02 um 00 39 39](https://user-images.githubusercontent.com/19797270/147862371-0618f595-f134-43d8-a582-7d05d4bd0066.png)

can you help me?

**Comment by danielwippermann** [comment]
Hi @lapixo !

Sorry for not getting back to you earlier, this issue has slipped through somehow.

Does the problem still exist or did you find a way to make it work?

Best regards,
Daniel

**Comment by lapixo** [comment]
Hi,
yes! I tried to connect to the KM2 Modul instead directly to my SLT. Now it works perfectly! Thank you for this cool project!!!!

**Comment by danielwippermann** [comment]
Thank you for the feedback! I'll close this issue, but feel free to open a new one if you need additional assistance!

Best regards, Daniel
