### ISSUE TITLE
Lacking documentation for `VBusRecordingConverter`

### ISSUE THREAD

**Issue by eightyeight** [danielwippermann/resol-vbus#7]
I'd like to use the `VBusRecordingConverter` to get data out of VBus dump files, but I can't figure out how to make it read a file! The furthest I've got is that I need to provide a `Buffer` to `rxBuffer` in the converter's constructor, but I'm unsure after that how to go about getting data out of the converter.

If you can point me in the right direction I'd be happy to write some documentation for the class, or provide a commented example!

**Comment by danielwippermann** [comment]
I've assembled a little tutorial under http://danielwippermann.github.io/resol-vbus/vbus-recording-converter-tutorial.html . Please feel free to reopen this issue or create a new one if you need any additional information.

**Comment by eightyeight** [comment]
Oh, I should have thought to try `pipe`! I'm a node newbie. Thanks very much for the super-quick help!
