### ISSUE TITLE
 I cannot seem to enjoy getting (and setting) values in the controller - Deltasol BX + KM2

### ISSUE THREAD

**Issue by tiele** [danielwippermann/resol-vbus#72]
Context - I have the Deltasol BX controller working with the KM2 interface.

What works (thank you!!)
-> getting the sensor values and publishing it to mqtt
-> getting device address with connection.waitForFreeBus(20000)

What doesn't work
-> I cannot seem to enjoy getting (and setting) values in the controller. Is this functionality available for BX controller?
// result is always null, 

connection.getValueIdByIdHash(deviceAddress, 0x7087886A).then(result => {
                        logger.debug('in result -> ' + JSON.stringify(result) );
                         //tried other getters too
                        // set the values using Connection#setValueById. didn't go so far as my result for get is always null
                    }); //

 // I found following in BX_3.03-Menu.xml (but i tried 3.02-Menu also)
        
            /**	<value id='Handbetrieb1' idHash='0x70878869' index='368'>
			<type id='VtHandbetrieb1' base='ManualMode' externalDescriptorFunc='true'>
				<default>0</default>
			</type>
		</value>
		<value id='Handbetrieb2' idHash='0x7087886A' index='369'>
			<type id='VtHandbetrieb2' base='ManualMode' externalDescriptorFunc='true'>
				<default>0</default>
			</type>
		</value>
		<value id='Handbetrieb3' idHash='0x7087886B' index='370'>
			<type id='VtHandbetrieb3' base='ManualMode' externalDescriptorFunc='true'>
				<default>0</default>
			</type>
		</value>
		<value id='Handbetrieb4' idHash='0x7087886C' index='371'>
			<type id='VtHandbetrieb4' base='Tristate'>
				<default>0</default>
			</type>
		</value>

**Comment by tiele** [comment]
double checked my version bx controller is 00_0010_7421_10_0100_052_2_0 => 2.0.1, that menu file doesn't include idHash

**Comment by tiele** [comment]
I clearly misunderstood the documentation if i use the  index and not the IdHash i have a working system! 

Thank you Daniel for this great library!! 5 sunny days coming up, couldn't be more pleased, i can now now 'red node script' my valve to pass the central heating through the sun boiler if warm enough, instead of using the heat pump. One for the planet! 

        client.on('message', (topic, payload) => {
            // Received Message: vbus/set 
            // on  { "hashId": 369, "value": 1 } handbediening R2
            // off { "hashId": 369, "value": 2 } handbediening R2
            logger.debug('Received Message: ' + topic + " " + payload.toString());
          
            const req = JSON.parse(payload);
            logger.debug('hashId: ' + req.hashId + " requested value: " + req.value);

            //waiting for the bus offering to get the address of the master device connected to the VBus
            const dgram = connection.waitForFreeBus(20000);
            //logger.debug('waitForFreeBus -> ' + dgram );
            dgram.then(datagram => {
                logger.debug('in result -> ' + JSON.stringify(datagram));
                if (datagram != null) {
                    const deviceAddress = datagram.sourceAddress;
                    
                    //  R2 --> on = 1 {"destinationAddress":32,"sourceAddress":29729,"minorVersion":0,"timestamp":"2022-03-03T15:06:09.636Z","command":256,"valueId":369,"value":1,"channel":0}  
                    //  R2 --> off = 2 ->{"destinationAddress":32,"sourceAddress":29729,"minorVersion":0,"timestamp":"2022-03-03T15:00:32.616Z","command":256,"valueId":369,"value":2,"channel":0}
               
                   /*connection.getValueIdHashById(deviceAddress, 369).then(result => {
                        logger.debug('in result 3!!!!-> ' + JSON.stringify(result) + ' Jos' );
                        // set the values using Connection#setValueById. didn't go so far as my result is always null
                    }); */
                    connection.setValueById(deviceAddress, req.hashId, req.value ).then(result => {
                        logger.debug('setting  ' + JSON.stringify(result));
                        connection.releaseBus(deviceAddress);
                    }); 
                }
            });
        })

**Comment by danielwippermann** [comment]
Thanks for the kind word and glad you got it working!
