### ISSUE TITLE
Deltasol LAN

### ISSUE THREAD

**Issue by dm82m** [danielwippermann/resol-vbus#73]
Hey @danielwippermann,

and again a questions from your Home Assistant Crew: we are currently able to get data from KM2 via cgi-bin. And we are also getting data from DL2/DL3. Is the LAN adapter also supporting to get the data? And if so: how?

Best,
Dirk

**Comment by danielwippermann** [comment]
Hi Dirk,

no, sorry, the VBus/LAN does not support an HTTP endpoint to get a snapshot of the current data.

If you want current data in conjunction with a VBus/LAN adapter you have to connect to port 7053 (VBus-over-TCP) and listen for incoming data for some period of time yourself.

If you want to implement something like this please have a look at the json-live-data-server example: https://github.com/danielwippermann/resol-vbus/blob/master/examples/json-live-data-server/index.js . It could serve as a starting point for your implementation.

Best regards,
Daniel
