### ISSUE TITLE
Home Assistant implementation

### ISSUE THREAD

**Issue by TheBazeman** [danielwippermann/resol-vbus#74]
Hi Daniel,  like your work! Very easy to implement it to Home Assistant. Maybe something for the readme?

Home Assistant implementation:

setup as described in: https://github.com/danielwippermann/resol-vbus/tree/master/examples/json-live-data-server

Home assistant configuration.yaml settings to add:

rest:
  - resource: http://127.0.0.1:3333/api/v1/live-data 
    scan_interval: 60
    sensor:
      - name: "Resol Temperature sensor 1"
        value_template: '{{value_json[0].rawValue | round(1)}}'
        unit_of_measurement: '°C' 
        json_attributes_path: "$[0]"
        json_attributes:
          - "name"
          - "rawValue"
      - name: "Resol Temperature sensor 2"
        value_template: '{{value_json[1].rawValue | round(1)}}'
        unit_of_measurement: '°C' 
        json_attributes_path: "$[1]"
        json_attributes:
          - "name"
          - "rawValue"
      - name: "Resol Temperature sensor 3"
        value_template: '{{value_json[2].rawValue | round(1)}}'
        unit_of_measurement: '°C' 
        json_attributes_path: "$[2]"
        json_attributes:
          - "name"
          - "rawValue"
      - name: "Resol Temperature sensor 4"
        value_template: '{{value_json[3].rawValue | round(1)}}'
        unit_of_measurement: '°C' 
        json_attributes_path: "$[3]"
        json_attributes:
          - "name"
          - "rawValue"
      - name: "Resol Temperature sensor 5"
        value_template: '{{value_json[4].rawValue | round(1)}}'
        unit_of_measurement: '°C' 
        json_attributes_path: "$[4]"
        json_attributes:
          - "name"
          - "rawValue"
      - name: "Resol Pump speed relay 1"
        value_template: '{{value_json[6].rawValue}}'
        unit_of_measurement: '%' 
        json_attributes_path: "$[6]"
        json_attributes:
          - "name"
          - "rawValue"
      - name: "Resol Pump speed relay 2"
        value_template: '{{value_json[7].rawValue}}'
        unit_of_measurement: '%'
        json_attributes_path: "$[7]"
        json_attributes:
          - "name"
          - "rawValue"

go to Home Assistant, configuration, server management --> Check configuration.

If ok, restart Home Assistant and the values should be available now. Search for "Resol" entities.

**Comment by danielwippermann** [comment]
Hi @TheBazeman,

thanks for that write-up. I decided to put it on a Wiki page in the repo:

https://github.com/danielwippermann/resol-vbus/wiki/HomeAssistant

I'll add a link to it both to the README and the documentation page soon.

Best regards, Daniel
