### ISSUE TITLE
Write data to Deltasol MX

### ISSUE THREAD

**Issue by ChR-iSz** [danielwippermann/resol-vbus#77]
I have a Deltasol MX with VBUS Adapter (USB).

It is possible to send data to the Deltasol MX ?

My plan: I will check the weather data (primary the sun data) for next 1-2 hourse before the burner will start (Temp: <=44•C).

If i see, as example, in the next 1-2 hours the sun will shining the stop/hold the start of the burner

It is possible ? The logic i can self  develop. The question is, how can i send to the deltasol MX or stop/hold the burning process ?

**Comment by danielwippermann** [comment]
Hi @ChR-iSz!

Sorry for replying late...

Yes, that is most likely possible. It mostly depends on your configuration and which piece of optional function you use for switching your burner.

The easiest way would be to change the manual mode of the relay / output that is connected to your burner. That way no signal would be forwarded even if your MX thinks it still switches the burner on.

The more secure way would be to find the internal ID of your burner function and check whether is has an 'Activated/Deactivated' option. Switching that has the advantage that other functions that rely on the burner activity (like parallel relays or function blocks) also see the correct state of the relay.

In both cases the "customizer" example should be a good starting point for such a tool:

Source: https://github.com/danielwippermann/resol-vbus/tree/master/examples/customizer
Documentation: http://danielwippermann.github.io/resol-vbus/#/md/docs/customizer-example

And that should already support the MX out-of-the-box. You only need to know which values to change. For that I offer you to send me a SET file from your controller together with the info which relay you want to switch. I'll then figure out the appropriate values.

Best regards,
Daniel

**Comment by ChR-iSz** [comment]
Hallo Daniel, danke. Können wir in Deutsch weiter kommunizieren ? Ich werde morgen versuchen das SET file zu erzeugen, und es Dir zu senden...

**Comment by ChR-iSz** [comment]
Hallo @danielwippermann Jetzt finde ich in Deinen Docs leider den link nicht mehr, zum erstellen des SET File...

**Comment by danielwippermann** [comment]
Huhu @ChR-iSz!
Du kannst die SET-Datei direkt am Regler über das Menü "Hauptmenu -> SD-Karte -> Einstellungen speichern" auf eine SD-Karte speichern. Alternativ geht der (aufwändigere) Weg über das RESOL Parameterization Tool (RPT).
