### ISSUE TITLE
KM2 API current_packets.vbus 

### ISSUE THREAD

**Issue by bigeddy51** [danielwippermann/resol-vbus#78]
Hallo Daniel,
gibt es eine Möglichkeit die current_packets.vbus meines KM2 zu entschlüsseln ?
Ich habe mittlerweile schon andere Methoden ausprobiert an die Daten des KM2 zu bekommen leider alles ohne Erfolg.
Auf telefonische Anfrage beim Support von Vbus.net bekam ich folgende Anwort auf meine Frage nach der API für das KM2: Man könnte nicht auch noch andere Systeme unterstützen oder supporten.
Ich hatte eigentlich vor das KM2 per API anzusprechen und diese Werte dann bei mir in der KNX Hausinstallations anzeigenzulassen bzw. weiterzuverarbeiten. Dies sollte dann über den Gira X1 erfolgen. Leider habe ich keine API Dokumentation vom KM2.
Ich nutze einen Kamin zur Warmwasseraufbereitung und Heizungsunterstützung. Die Steuerung erfolgt über den Resol Delta Therm FK und das KM2 greift die Daten ab.

**Comment by danielwippermann** [comment]
Hi @bigeddy51 !

Der Aufbau der `current_packets.vbus`-Datei ist in dem Dokument über das [VBus Recording File Format](http://danielwippermann.github.io/resol-vbus/#/md/docs/vbus-recording-file-format) beschrieben.

Ein Beispiel für ein Tool, das diese Datei z.B. nach JSON umwandeln kann, findest Du im `formatter`-Beispiel des `resol-vbus.rs`-Repos: https://github.com/danielwippermann/resol-vbus.rs/tree/master/examples/formatter

Wenn Du kein externes Tool nutzen willst: das KM2 (zumindest die aktuelle 2.x.x) hat eigentlich auch ein Web-API für die JSON-Konvertierung an Bord. Das besteht im Prinzip aus drei Schritten:

1. Einloggen
2. Daten abrufen
3. Ausloggen

Das Einloggen geht mit einem POST-Request an das KM2:

```
POST http://127.0.0.1:9000/cgi-bin/resol-webservice
Content-Type: application/json

{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "login",
    "params": {
      "username": "admin",
      "password": "secretpassword"
    }
}
```

Daraufhin bekommst Du eine "authId" zurück, die Du in den folgenden Requests einsetzen musst.

Daten abrufen und ausloggen geht dann über den folgenden kombinierten Request:

```
POST http://xxx.xxx.xxx.xxx/cgi-bin/resol-webservice
Content-Type: application/json

[{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "dataGetCurrentData",
    "params": {
        "authId": "......"
    }
}, {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "logout",
    "params": {
        "authId": "......"
    }
}]
```

**Comment by bigeddy51** [comment]
Hey Daniel,
Danke für die schnelle Rückmeldung.
Ich habe gerade gesehen das auf dem KM 2 die Firmware 1.2.0 ist. Laut der Resol Homepage gibt es auch keine aktuellere Firmware. Weißt du zufällig woher ich die Firmware 2.x.x. bekommen kann ?

**Comment by danielwippermann** [comment]
Hi @bigeddy51,

Dein KM2 kannst Du leider nicht auf Firmware 2.x.x updaten. Es gibt seit Anfang 2022 ein neues KM2, das auf einer neu entwickelten Hardware basiert. Alte (Firmware 1.x.x) und neue (Firmware 2.x.x) KM2s sind deshalb nicht kompatibel.

Die Requests aus der Antwort oben müssten aber auch mit Firmware 1.2.0 funktionieren.

**Comment by bigeddy51** [comment]
Hey Daniel,

Die Anfrage per Port 9000 funktioniert leider nicht. 
Wenn ich das KM2 direkt per http://xxx.xxx.xxx.xxx/cgi-bin/resol-webservice anpreche bekomme ich als Antwort:
{ "error": { "category": "App", "message": "No path info given" } }
Ich denke mir fehlt einfach die authid. Diese bekomme ich aber leider nicht durch das Anprechen von POST http://127.0.0.1:9000/cgi-bin/resol-webservice

**Comment by bigeddy51** [comment]
Hey Daniel,
Ich habe s jetzt hinbekommen mit der Linux Kommandozeile.
Ist es richtig das man sich mit der authId einloggen kann, dann kann ich die Werte einsehen. Wenn ich jetzt aber nochmals die Werte aktualisiert haben möchte, dann benötige ich wieder eine neue authId ?
Es gibt für meinen Gira X1 einen Logikbaustein Web Request. Mit diesem Baustein wollte ich das KM2 ansprechen. Die Werte rausfiltern und diese dann auslesen. Problem wäre jetzt natürlich die ständig änderne authId für einlogen. 
Die Logik Bausteine für den Gira X1 werden in C# geschrieben.
Oder hast du eventuell eine Vorlage die das KM2 anpricht Step by Step, also erst die authId abfragt und dann sichmit dieser einloggt und sich dann wieder ausloggt.

**Comment by danielwippermann** [comment]
Hi @bigeddy51!

>  Ist es richtig das man sich mit der authId einloggen kann, dann kann ich die Werte einsehen. Wenn ich jetzt aber nochmals die Werte aktualisiert haben möchte, dann benötige ich wieder eine neue authId ?

Jein. Streng genommen musst Du die authId nicht jedes Mal neu erzeugen, wenn das Gerät nicht neustartet und Du in regelmäßigen Abständen die authId z.B. zum Abrufen von Daten benutzt. Denn dadurch verlängert sich immer ein Timeout, der beim Ablaufen die authId löscht.

Wenn Du es also so programmieren kannst, dass sich Dein System immer die letzte authId merkt, es erst mit der probiert und im Falle eines Authentication-Fehlers sich eine neue holt, kannst Du wahrscheinlich auf das häufige Aus- und Wiedereinloggen verzichten.

> Oder hast du eventuell eine Vorlage die das KM2 anpricht Step by Step, also erst die authId abfragt und dann sichmit dieser einloggt und sich dann wieder ausloggt.

Ja, habe ich mal aus ein paar Beispielen aus dem Internet zusammenkopiert:

```
using System;
using System.Net;
using System.IO;
using System.Text;
using System.Text.Json;

namespace Km2Fetch
{
    class Program
    {
        static async Task Main(string[] args)
        {
            // TODO(daniel): change this to the actual KM2 host
            var url = "http://127.0.0.1:3333/cgi-bin/resol-webservice";

            // TODO(daniel): change this to the KM2's web password
            var password = "admin1234";

            using var client = new HttpClient();

            var loginResult = await PostJsonRpc(client, url, "login", "{\"username\":\"admin\",\"password\":\"" + password + "\"}");

            var authId = loginResult.GetProperty("authId").GetString();

            var dataResult = await PostJsonRpc(client, url, "dataGetCurrentData", "{\"authId\":\"" + authId + "\"}");

            await PostJsonRpc(client, url, "logout", "{\"authId\":\"" + authId + "\"}");

            Console.WriteLine(dataResult);
        }

        static async Task<JsonElement> PostJsonRpc(HttpClient client, string url, string method, string requestParams)
        {
            var request = "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"" + method + "\",\"params\":" + requestParams + "}";
            var requestContent = new StringContent(request, Encoding.UTF8, "application/json");
            var httpResponse = await client.PostAsync(url, requestContent);
            var response = await httpResponse.Content.ReadAsStringAsync();
            var responseDocument = JsonDocument.Parse(response);
            var result = responseDocument.RootElement.GetProperty("result");
            return result;
        }
    }
}
```

Ist schon ein bischen was her, seit ich aktiv C# programmiert habe, also sieh mir nach, wenn das nicht State-of-the-Art ist...

Das Programm loggt sich ein, liest die Live-Daten aus, loggt sich wieder aus und gibt dann die Live-Daten auf der Konsole raus. Aber der Kreativität mit dem Weiterverarbeiten sind hier natürlich keine Grenzen gesetzt :)

Ich hoffe, das Beispiel hilft ein bischen weiter.

**Comment by bigeddy51** [comment]
Hey Daniel,
Super Vielen Dank für deine Mühe und Hilfe.
Mal sehen wie wie fern dein C# noch vorhanden ist :-)
Ich werde mich die Tage ransetzen und probieren mir einen Baustein (Logik) für meinen Gira X1 mit Virtual Studio zu schnitzen.
