### ISSUE TITLE
Integrate em-simulator into json-live-data-server

### ISSUE THREAD

**Issue by chiefdeputy** [danielwippermann/resol-vbus#86]
Hi,
not really a issue more a feature suggestion:

Is it possible to integrate the em-simulator as (POST) endpoint into the json-live-data-server?

E.g.:
```
POST -> http://127.0.0.1:3333/api/v1/em/<EmSubAddress>/sensor/<sensorId>/resistance
{
    "value": int (resistant)
}
```

```
POST -> http://127.0.0.1:3333/api/v1/em/<EmSubAddress>/sensor/<sensorId>/bas
{
    "temperature": float
    "mode": int
}
```

```
GET -> http://127.0.0.1:3333/api/v1/em/<EmSubAddress>/relay/<relayId>
{
    "value": int
}
```

Unfortunately, I'm no Java(Script) guy, so I did not manage to get it together.
This would make the integration of Resol devices into Home Assistant etc. much easier and provide a lot of new possibilities.

Thank you for your work! And as I said, just a suggestion, no pressure :)

**Comment by danielwippermann** [comment]
Hi @chiefdeputy !

Thanks for that suggestion. I have added that functionality in commit a0115021f02e0ff5fc4396d41af88219e095655a. Please give it a try and report any issues here.

Thanks! Daniel

**Comment by chiefdeputy** [comment]
Wow, that was fast.
Unfortunately I'm away from home for the next 4 weeks. I'll test it then.

@dm82m: I'm thinking of forking your Home Assistant addon to test it.
If the tests are succefull, I'll open a pull request. 😉

**Comment by dm82m** [comment]
@chiefdeputy you can just install the addon, it will use the latest commit so it should be there. But yes, if changes are needed, you can just raise an pr.

what usecase are you thinking of?

**Comment by chiefdeputy** [comment]
Hi,
sorry it took so long.
But I can confirm that my Deltasol MX is able to read the states of a simulated EM!

Tested using the Home Assistant addon of @dm82m with a RESTful Command entity.
