### ISSUE TITLE
Resol MX hat zwei Device Adressen

### ISSUE THREAD

**Issue by SurfGargano** [danielwippermann/resol-vbus#94]
Im IOBroker Resol Adapter (der vom grizzelbee) kann man auch Daten setzen. Das klappt auch gut bei Devices die nur eine Adresse haben.

Der Resol MX hat aber zwei Device Adressen :
0x7E11 und 0x7E21.
0x7E11 ist im Optimizer vorhanden, 0x7E21 jedoch nicht. Dafür gibt es kein Optimizer File.
0x7E21 (32289) ist jedoch für Heizkreis 1 vorgesehen, welches ein User steuern möchte.
![image](https://github.com/danielwippermann/resol-vbus/assets/70272783/b1270cee-9c53-431e-acf5-859b67282e69)

Die Daten sehen so aus : (Auszug aus dem Result vom HeaderSetConsolidator handler)

`"deviceId":"007E110010","addressId":32273,"unitId":"DegreesCelsius","unitText":" °C","typeId":"Number_0_1_DegreesCelsius","precision":1,"rootTypeId":"Number","parts":[{"offset":0,"mask":255,"bitPos":0,"isSigned":false,"factor":1},{"offset":1,"mask":255,"bitPos":0,"isSigned":true,"factor":256}]}`

`"deviceId":"007E210010","addressId":32289,"unitId":"None","unitText":"","typeId":"Number_1_None","precision":0,"rootTypeId":"Number","parts":[{"offset":2,"mask":255,"bitPos":0,"isSigned":false,"factor":1}]}`

Wie kann ich da weitermachen, daß ich den Heizkreis setzen kann ? Benötige ich einen Optimizer File für 0x7E21 ?

**Comment by danielwippermann** [comment]
Hi @SurfGargano !

> Wie kann ich da weitermachen, daß ich den Heizkreis setzen kann ? Benötige ich einen Optimizer File für 0x7E21 ?

Nein, die Heizkreis-Parameter sind auch im Optimizer für 0x7E11 enthalten. Ihr Name beginnt dann mit `Heizung_Heizkreis1_...`.

**Comment by SurfGargano** [comment]
Leider funktioniert das nicht so recht : Dieser Fehler wird ausgeworfen
`Error : Unable to complete value {"key":0;"value":{"valueId":"Heizung_Heizkreis1_Betriebsart"}}`
Ich hab die entsprechende Stelle im Code gefunden, aber da weiß ich nicht recht was die Ursache ist.
 
Das Problem ist bei einem User mit dem MX Resol, bei mir mit dem CX Resol funktioniert dies einwandfrei.

**Comment by SurfGargano** [comment]
Habs jetzt selber rausgefunden: Beim createOptimizer muss man die Version mit angeben

` const options1 = {
                    deviceAddress : context.deviceAddress,
                    deviceMajorVersion : 2
                }
  const optimizer = await vbus.ConfigurationOptimizerFactory.createOptimizer(options1);`
