### ISSUE TITLE
Wie kann ich die deviceMajorVersion vom MX Controller  bekommen ?

### ISSUE THREAD

**Issue by SurfGargano** [danielwippermann/resol-vbus#96]
Ein User vom Resol Adapter hat den MX V2. Wie ich jetzt rausgefunden habe, benötigt createOptimizer unter options die Angabe deviceMajorVersion.

Wie kann ich die deviceMajorVersion vom MX Controller bekommen ?
[EDIT] Hab gesehen, die kann man nicht bekommen.

Kannst Du absehen, wann Du dies umsetzen kannst ?
Short-term plans
Remove current ConfigurationOptimizer constructs in favor of RESOL's official support.

**Comment by danielwippermann** [comment]
Hi @SurfGargano !

> Wie kann ich die deviceMajorVersion vom MX Controller bekommen ?

Die Major-Version selber ist leider nicht auslesbar aus dem Regler. Die einzige Versions-Info, an die man über den VBus kommt, ist die "Changeset-ID", ein für eine Firmware-Version eindeutiger, aber relativ zufälliger Wert (sprich: steigt nicht monoton an, sondern springt wild im 32-Bit-Zahlenraum herum).

Was man also jetzt machen könnte, wäre eine Liste der wenigen, bekannten Changeset-IDs zu ermitteln und dann eine Hilfsfunktion anzubieten, die diese Changeset-ID vom Regler abfragt und in der Liste nachschlägt, um welche Version es sich handeln könnte. Das umfasst dann natürlich nur bisher offiziell veröffentlichte Versionen und würde bei einer Prototyp-Firmware bzw. einer zukünftigen Version nicht ordentlich funktionieren, aber das ist vermutlich im Feld ja erst einmal kein Problem.

Es gäbe noch einen alternativen Ansatz, den Regler nach Infos über Werte zu fragen, die es in Version 1.xx nicht gibt, in Version 2.xx aber wohl, dann könnte man die Diffenzierung darüber machen. Aber der hat andere Nachteile, von daher würde ich davon abraten.

> Kannst Du absehen, wann Du dies umsetzen kannst ?

Nein, zumal es das Problem hier nicht behebt, weil man selbst dann noch wissen muss, welche Major-Version vorhanden ist (RESOL pflegt für die beiden Major-Versionen unterschiedliche Optimizer-Dateien).

Wäre diese oben erwähnte Funktion hilfreich für die Erfüllung Deiner Problemstellung?

Bis dann,
Daniel

**Comment by SurfGargano** [comment]
Hallo Daniel,

 

das ist leider nicht so gut, daß man die MajorVersion nicht auslesen kann.

Da wir den Adapter allgemeingültig halten wollen, bleibt nur die Auswahl durch den User. Das habe ich mit Grizzelbee schon diskutiert.

 

Danke und viele Grüße

Werner

 

 

Von: danielwippermann ***@***.***> 
Gesendet: Mittwoch, 13. Dezember 2023 12:53
An: danielwippermann/resol-vbus ***@***.***>
Cc: Gargano ***@***.***>; Mention ***@***.***>
Betreff: Re: [danielwippermann/resol-vbus] Wie kann ich die deviceMajorVersion vom MX Controller bekommen ? (Issue #96)

 

Hi @SurfGargano <https://github.com/SurfGargano>  !

Wie kann ich die deviceMajorVersion vom MX Controller bekommen ?

Die Major-Version selber ist leider nicht auslesbar aus dem Regler. Die einzige Versions-Info, an die man über den VBus kommt, ist die "Changeset-ID", ein für eine Firmware-Version eindeutiger, aber relativ zufälliger Wert (sprich: steigt nicht monoton an, sondern springt wild im 32-Bit-Zahlenraum herum).

Was man also jetzt machen könnte, wäre eine Liste der wenigen, bekannten Changeset-IDs zu ermitteln und dann eine Hilfsfunktion anzubieten, die diese Changeset-ID vom Regler abfragt und in der Liste nachschlägt, um welche Version es sich handeln könnte. Das umfasst dann natürlich nur bisher offiziell veröffentlichte Versionen und würde bei einer Prototyp-Firmware bzw. einer zukünftigen Version nicht ordentlich funktionieren, aber das ist vermutlich im Feld ja erst einmal kein Problem.

Es gäbe noch einen alternativen Ansatz, den Regler nach Infos über Werte zu fragen, die es in Version 1.xx nicht gibt, in Version 2.xx aber wohl, dann könnte man die Diffenzierung darüber machen. Aber der hat andere Nachteile, von daher würde ich davon abraten.

Kannst Du absehen, wann Du dies umsetzen kannst ?

Nein, zumal es das Problem hier nicht behebt, weil man selbst dann noch wissen muss, welche Major-Version vorhanden ist (RESOL pflegt für die beiden Major-Versionen unterschiedliche Optimizer-Dateien).

Wäre diese oben erwähnte Funktion hilfreich für die Erfüllung Deiner Problemstellung?

Bis dann,
Daniel
