### ISSUE TITLE
Main function returned with error: undefined

### ISSUE THREAD

**Issue by fliix-de** [danielwippermann/resol-vbus#97]
Hallo Daniel, danke für diese tolle Anwendung.

Ich schaffe es leider nicht, die Anwendung stabil zum Laufen zu bekommen.

Manchmal läuft die Anwendung fehlerfrei und das JSON ist erreichbar. Nach einem Neustart lässt sich die Anwendung dann nicht mehr starten:

Main function returned with error: undefined

![grafik](https://github.com/danielwippermann/resol-vbus/assets/43872194/a05ca390-45cc-4a0b-95ee-13097c493a1e)

Ich bin neu im NodeJS Umfeld, daher die Bitte der Nachsicht.

Hast du eine Idee, was die Ursache sein könnte?

Installiert innerhalb von einem Debian Docker (latest bookworm):
npm -v 10.2.4
node -v 21.5.0

Nach ca. 20 Versuchen, hat es dann wieder geklappt. Nutze ich die falsche node Version?

![grafik](https://github.com/danielwippermann/resol-vbus/assets/43872194/ae7ff85b-e031-48cd-a29e-1a61725f4a32)

**Comment by danielwippermann** [comment]
HI @fliix-de !

Hmmm, "error: undefined"... Ja, wirklich sehr hilfreich... :)

Ok, ich bekomme so eine Fehlermeldung auch hin, wenn ich einen Konfigurationsfehler einbaue, aber das wird ja nicht direkt auf Dich übertragbar sein, weil es bei Dir ja ab und zu dann doch ohne Änderung an der config.js zu funktionieren scheint. 

![grafik](https://github.com/danielwippermann/resol-vbus/assets/1997538/9afe49b9-3715-4240-9ee3-bc3d4531abd1)

Ich versuche jetzt erstmal rauszufinden, wie ich die Fehlermeldung etwas "informativer" bekomme. Dann melde ich mich nochmal...

**Comment by danielwippermann** [comment]
Es scheint so zu sein, dass die Formatierungfunktion von `logger.error` nicht damit zurecht kommt, wenn man ein JavaScript-`Error`-Objekt da rein reicht. Könntest Du in Deiner `index.js`mal folgende Änderung machen (oder aber das git-Repo pullen, da habe ich die Änderung auch gemacht):

https://github.com/danielwippermann/resol-vbus/commit/bb428ca7f0fcadd5ba2e154af8267d67784ee0ef

Dann sehen die Fehlermeldungen etwas informativer aus:

![grafik](https://github.com/danielwippermann/resol-vbus/assets/1997538/da0df734-115a-4f34-988e-a44a8e84409f)

Ggf. finden wir so den eigentlichen Grund für die Fehler etwas einfacher...

**Comment by fliix-de** [comment]
Erstmals vielen Dank, dass du dir die Mühe gemacht hast. Ich stehe gerade etwas auf dem Schlauch.
Ich habe deine Änderung eingetragen und erhalte jetzt die gleiche Fehlermeldung, wie in deinem Screenshot.

Docker neu gestartet. 1. Versuch: sofort eine Verbindung hergestellt. 2./3./4./5. Versuch: Fehlermeldung

![grafik](https://github.com/danielwippermann/resol-vbus/assets/43872194/14703af7-0a4e-4a83-a0fc-cd643a737824)

Ich habe gerade auch mein altes Script auf Basis von ioBroker weiterlaufen lassen, hier läuft es stabil. Da der Fehler in der "TCP-Connection" auftritt, wollte ich das parallel testen.

Hast du noch irgendeine Idee, warum es dazu kommen könnte?

**Comment by danielwippermann** [comment]
Was für ein LAN-Gateway benutzt Du? Wenn Du ein VBus/LAN-Adapter verwendest, ist die vermutlichste Ursache, dass dieser Adapter nur eine VBus/TCP-Verbindung gleichzeitig erlaubt. Wenn also jetzt im Hintergrund noch ein anderes Skript daraufzugreift oder aber (bezogen auf Deinen Screenshot) der VBus/LAN-Adapter noch nicht mitbekommen hat, dass die Verbindung vom oberen Aufruf eigentlich beendet ist und erstmal Zeit verstreichen muss, bis der VBus/LAN-Adapter das realisiert und bis dahin keine weitere Verbindung zulässt. Ist aber alles nur Vermutung, ich hatte das hier mit einem DL2 Plus getestet und der erlaubt 10 gleichzeitige Verbindungen und gibt eine wohlklingende Fehlermeldung zurück, wenn diese Grenze erreicht ist.

Andere mögliche Ursachen für das "Unable to connect" wären noch klassische Netzwerkprobleme zwischen PC und Adapter und Probleme mit der Spannungsversorgung, aber diese zwei Kategorien schließe ich aufgrund Deiner Schilderung erstmal aus.

**Comment by fliix-de** [comment]
Ich verwende den: Schnittstellenadapter VBus®/LAN.

Und ja das klingt logisch, dass der Adapter noch nicht realisiert hat, dass die Verbindung geschlossen wurde. Allerdings war der Test mit dem ioBroker Skript erst nach meinem Screenshot, sprich da sollte eigentlich nichts anderes im Hintergrund laufen. In diesem Fall wahrscheinlich mein STRG-C und dann zu schnell erneut versucht. Hatte das System jetzt gerade 15 Minuten unangetastet und das Script lief wieder sauber. Erneutes beenden und starten führte wieder zum Fehler. Sieht fast danach aus.

Ich werde das weiter beobachten. Danke für deine Unterstützung.
